"""Authored lesson notes, mathematical examples and experiments for Chapters 2–18."""

CONTENT = {
    2: dict(
        overview="Computer vision turns measurements into arrays and optimizes rules over those arrays. A scalar is one number; a vector is an ordered list; a matrix is a rectangular table. The same notation will later describe pixels, camera coordinates, weights and gradients.",
        titles=[
            "Arrays, linear maps and eigenvectors",
            "Derivatives, gradients and optimization",
            "Probability, statistics and frequency",
        ],
        lessons=[
            "A dot product multiplies corresponding entries and adds them: it measures alignment. Matrix multiplication combines rows with columns and composes linear maps. An eigenvector keeps its direction under a map; its eigenvalue is the scale factor. Symmetric covariance matrices have orthogonal eigenvectors, which makes PCA a rotation toward directions of variation.",
            "A derivative measures how a function changes when its input moves a little. A partial derivative changes one input while holding the others fixed. Collect the partial derivatives into a gradient. Gradient descent subtracts a small multiple of this gradient. Backpropagation is an efficient way of applying the chain rule, not a different derivative.",
            "Probability describes uncertain outcomes; the mean describes a center and variance describes spread. A finite sample estimates these quantities with uncertainty. The Fourier transform rewrites a signal as weighted sinusoids. A large spectral coefficient means that a repeating pattern at that frequency is present; it does not specify an object category.",
        ],
        math=r"w_{t+1}=w_t-\eta\,2(w_t-1)",
        symbols="For loss L(w)=(w−1)², w is the current parameter, t the update number and η the positive learning rate. At w=3 and η=0.1, the gradient is 4, so the next value is 2.6.",
        example="w = 3.0\nlearning_rate = 0.1\ngradient = 2 * (w - 1)\nw_next = w - learning_rate * gradient\nassert abs(w_next - 2.6) < 1e-12\nprint(w_next)",
        internals="The lab checks an eigendecomposition numerically, compares finite differences with an analytic derivative, and detects a sinusoid through an FFT. The FFT uses complex coefficients; magnitude discards phase.",
        experiment="Change the gradient-descent step from 0.1 to 0.3, then derive the stability interval for the quadratic before trying a larger step.",
        pitfall="Elementwise multiplication A*B is not matrix multiplication A@B. A low loss after one example says nothing about generalization.",
        challenge="Build a two-parameter least-squares line fitter, derive both partial derivatives, and compare iterative updates with a closed-form solution.",
        reference="https://numpy.org/doc/stable/reference/routines.linalg.html",
        scratch="numerics.softmax",
    ),
    3: dict(
        overview="Imagine an image as a spreadsheet. A grayscale cell holds one intensity; an RGB pixel holds three channel values. Sampling chooses where measurements are taken, and quantization chooses which intensity values can be represented. The array is the measurement, not the scene itself.",
        titles=[
            "Pixels, coordinates and channels",
            "Bit depth and quantization error",
            "Resolution, alpha and tensor layout",
        ],
        lessons=[
            "Array indexing uses row then column, so image[y, x] is a pixel at horizontal position x and vertical position y. RGB has three channels; RGBA adds alpha, an opacity value. Grayscale is a weighted summary of color, not simply the first channel. OpenCV commonly stores BGR while plotting libraries expect RGB.",
            "An unsigned 8-bit channel represents integers from 0 to 255. Reducing intensity levels creates banding even if image width and height stay fixed. Convert to floating point before arithmetic, because integer overflow can wrap around. Float image arrays conventionally use 0 to 1 when displayed as color.",
            "Resolution describes the sampling grid. Reducing it loses spatial information; enlarging it cannot recover missing detail. Alpha compositing combines foreground and background using opacity. HWC and CHW contain the same values in different axis orders; reshape alone does not perform this permutation. Metadata such as EXIF orientation can change intended display.",
        ],
        math=r"C=\alpha F+(1-\alpha)B",
        symbols="C is the composited channel, F foreground intensity, B background intensity, and α opacity between zero and one. Half-opacity red over white gives RGB [1, 0.5, 0.5] in normalized units.",
        example="foreground = np.array([1., 0., 0.])\nbackground = np.ones(3)\nalpha = 0.5\ncomposite = alpha * foreground + (1 - alpha) * background\nassert np.allclose(composite, [1., .5, .5])\nprint(composite)",
        internals="The experiments separate channels, quantize levels with rounding, resample the spatial grid and transpose axes. Image dimensions and memory size are measured from the actual array.",
        experiment="Reduce the number of intensity levels while leaving resolution fixed. Then reduce resolution with all 256 levels. Describe how the two artifacts differ.",
        pitfall="Pixel coordinates are not Cartesian world coordinates: y normally increases downward. Alpha is not another visible color channel.",
        challenge="Write an image inspector that reports format, size, dtype, channel order and memory, and rejects ambiguous two-channel arrays.",
        reference="https://pillow.readthedocs.io/en/stable/handbook/concepts.html",
        scratch="numerics.gray",
    ),
    4: dict(
        overview="OpenCV supplies optimized building blocks for images and video. Its functions still have contracts: channel order, data type, coordinate convention and return values. Learning these contracts prevents a successful function call from silently producing the wrong image.",
        titles=[
            "Read, write, draw and label",
            "Resizing and image display",
            "Events, camera loops and controls",
        ],
        lessons=[
            "Read an image, check decoding succeeded, and convert BGR to RGB before plotting. Drawing modifies an array in place unless you copy it first. PNG is lossless for the lab arrays; JPEG can change values. The notebook performs an encode/decode round trip so image I/O can be tested without external assets.",
            "Resizing interpolates a sampled grid. INTER_AREA is often useful when shrinking; nearest-neighbor preserves discrete labels in masks. Matplotlib can display images inside notebooks without a desktop window. Desktop imshow requires a GUI-enabled OpenCV build and an event loop that calls waitKey.",
            "A camera loop repeatedly reads a frame, checks success, processes it and releases the device in a finally block. Mouse callbacks receive events and coordinates; trackbars expose integer parameters. The notebook simulates a threshold control for headless execution. scripts/opencv_interactive.py supplies actual paint, trackbar and webcam modes on desktop systems.",
        ],
        math=r"I_{RGB}(y,x)=[I_{BGR}(y,x,2),I_{BGR}(y,x,1),I_{BGR}(y,x,0)]",
        symbols="I is an image indexed by row y, column x and channel index. Reversing the three BGR channels gives RGB. BGR [10,20,200] becomes RGB [200,20,10].",
        example="bgr = np.array([[[10, 20, 200]]], dtype=np.uint8)\nrgb = cv2.cvtColor(bgr, cv2.COLOR_BGR2RGB)\nassert rgb[0, 0].tolist() == [200, 20, 10]\nprint(rgb)",
        internals="OpenCV decoding produces an array, drawing edits its buffer, and encoding compresses that buffer to bytes. VideoCapture abstracts a file or device; read success is independent of the requested frame size.",
        experiment="Save the same RGB image as PNG and JPEG, reload both, and measure the maximum absolute difference after casting to signed integers.",
        pitfall="cv2.imread returns None on many failures. A missing camera or display is an environmental condition, not evidence that the vision algorithm is wrong.",
        challenge="Build a desktop paint application with undo, color selection and a save action that reports failures clearly.",
        reference="https://docs.opencv.org/4.x/d6/d00/tutorial_py_root.html",
        scratch="numerics.gray",
    ),
    5: dict(
        overview="Filtering replaces a pixel using its neighborhood. Think of a small window sliding across a spreadsheet. The weights in that window form a kernel. Different weights preserve, blur or emphasize different spatial patterns, and boundary handling changes the answer near image edges.",
        titles=[
            "Correlation and weighted neighborhoods",
            "Gaussian noise and smoothing",
            "Impulse noise and nonlinear filters",
        ],
        lessons=[
            "Correlation multiplies each neighborhood by a kernel and sums the products. Mathematical convolution flips the kernel first. OpenCV filter2D and deep-learning convolution layers implement correlation. Symmetric kernels hide the distinction. A mean filter assigns equal weight to every location; its weights sum to one so constant regions stay constant.",
            "Gaussian noise adds a random value to each measurement. A Gaussian filter weights nearby pixels more heavily than distant ones. Sigma controls the spread and kernel size truncates its support. Separable Gaussian filtering performs horizontal and vertical passes to reduce arithmetic. The lab compares explicit loops with OpenCV using matching replicate borders.",
            "Salt-and-pepper noise creates extreme pixels, so an average spreads the corruption. Median filtering selects the middle neighborhood value and often handles impulses better. Bilateral filtering also weights intensity similarity to preserve some edges. Speckle is multiplicative noise; its magnitude grows with signal intensity. No single filter solves every noise process.",
        ],
        math=r"Y_{ij}=\sum_{u=-r}^{r}\sum_{v=-r}^{r}K_{uv}X_{i+u,j+v}",
        symbols="X is the input, K the kernel, Y the result, and r the window radius. A 3×3 mean kernel has nine weights of 1/9. A neighborhood containing values 1 through 9 therefore produces 5.",
        example="patch = np.arange(1, 10, dtype=float).reshape(3, 3)\nkernel = np.ones((3, 3)) / 9\nvalue = np.sum(patch * kernel)\nassert np.isclose(value, 5)\nprint(value)",
        internals="The reference implementation pads explicitly and loops over pixels. OpenCV uses optimized kernels and vectorized hardware. Match dtype, correlation convention and border mode before comparing results.",
        experiment="Use equal noise seeds to compare mean, Gaussian and median filtering. Report MSE against the clean synthetic image and also inspect whether thin edges disappear.",
        pitfall="Smoothing may lower noise while removing a real small object. Numerical equality comparisons are invalid when border modes differ.",
        challenge="Design an image restoration lab that chooses among three filters from measured noise statistics and reports failure cases.",
        reference="https://docs.opencv.org/4.x/d4/d13/tutorial_py_filtering.html",
        scratch="numerics.correlate",
    ),
    6: dict(
        overview="Enhancement changes appearance so a useful signal is easier to inspect or process. Brightness shifts intensity, contrast changes separation, and a histogram counts how often each intensity occurs. Enhancement should serve a task; a visually dramatic image is not automatically more informative.",
        titles=[
            "Histograms and equalization",
            "Local contrast with CLAHE",
            "Gamma and unsharp masking",
        ],
        lessons=[
            "A histogram ignores spatial arrangement and counts intensity values. Equalization maps intensities through a cumulative distribution so a narrow range spreads more widely. The implementation subtracts the first nonzero cumulative count so a dark lower endpoint maps to zero. A constant image needs special handling because there is no intensity range to expand.",
            "Global equalization uses one mapping for the whole image. CLAHE divides an image into tiles, clips excessive histogram counts and interpolates neighboring mappings. The clipping limit controls noise amplification. Apply local contrast carefully: a textureless low-light region may contain noise rather than hidden detail.",
            "Gamma correction is a nonlinear pointwise map. With normalized input and the convention output=input**gamma, gamma below one brightens midtones. Unsharp masking adds a scaled difference between the original image and a blurred copy. Both clipping and color-space choices affect the result; sharpening can create halos around edges.",
        ],
        math=r"y=x^\gamma\quad (0\le x\le1)",
        symbols="x is normalized input intensity, y the corrected intensity and γ the chosen exponent. With x=0.25 and γ=0.5, y=0.5. This definition must be stated because some tools expose reciprocal gamma.",
        example="x = np.array([0., .25, .5, 1.])\ngamma = 0.5\ny = x ** gamma\nassert np.isclose(y[1], .5)\nprint(y)",
        internals="The lab computes a NumPy CDF mapping, compares OpenCV equalization, then examines CLAHE and sharpening. The plotted histograms show counts, not probabilities unless normalized.",
        experiment="Increase CLAHE strength on a noisy flat region and quantify both local contrast and noise variance. Find a setting that improves the downstream threshold mask.",
        pitfall="Equalizing R, G and B independently can change hue. Clipping after sharpening discards values and can hide overshoot.",
        challenge="Build an enhancement studio with saved parameter presets and a side-by-side comparison on dark, backlit and noisy images.",
        reference="https://docs.opencv.org/4.x/d5/daf/tutorial_py_histogram_equalization.html",
        scratch="numerics.equalize",
    ),
    7: dict(
        overview="Geometric transformations move coordinates rather than directly changing intensity. A camera sees perspective, while image editing may only need translation or rotation. Separating coordinate mapping from interpolation explains why correct geometry can still produce blurry pixels.",
        titles=[
            "Translation, rotation and inverse mapping",
            "Homographies from correspondences",
            "Interpolation and document rectification",
        ],
        lessons=[
            "Translation adds an offset; rotation mixes x and y around a chosen center. Homogeneous coordinates append a one, allowing translation and linear transformation in a single matrix. Image warping usually asks which source position produced each destination pixel, avoiding holes that forward scatter can leave.",
            "An affine transform preserves parallel lines. A homography is a projective map represented by a 3×3 matrix up to scale; it can describe one plane viewed from another camera. Four point pairs in a nondegenerate arrangement provide eight independent equations. Normalized DLT improves conditioning before solving a homogeneous linear system by SVD.",
            "Nearest-neighbor chooses one sample; bilinear interpolation blends four samples. Interpolation does not recover lost detail. Document rectification estimates a homography from ordered page corners and resamples the page into a rectangle. Nonplanar pages, lens distortion and inaccurate corners violate the simple model.",
        ],
        math=r"\tilde p\prime=H\tilde p,\qquad p\prime=(q_x/q_z,q_y/q_z)",
        symbols="p is an input point, the tilde appends a homogeneous one, H is a 3×3 map and q is the resulting homogeneous vector. Translation by (3,−2) sends (4,5) to (7,3). Divide by the third coordinate after a perspective map.",
        example="point = np.array([4., 5., 1.])\nH = np.array([[1., 0., 3.], [0., 1., -2.], [0., 0., 1.]])\nq = H @ point\nxy = q[:2] / q[2]\nassert np.allclose(xy, [7, 3])\nprint(xy)",
        internals="The reference normalizes point clouds, builds the DLT design matrix, takes the last right singular vector and denormalizes H. OpenCV warpPerspective then performs sampling with that matrix.",
        experiment="Perturb one corner by two pixels and visualize the interior displacement. Compare nearest and bilinear interpolation on a checkerboard.",
        pitfall="A homography cannot generally align a scene with multiple depths under translation. Wrong corner order can fold the page across itself.",
        challenge="Build a document scanner that detects corners, checks quadrilateral quality and exports a rectified image with a failure explanation.",
        reference="https://docs.opencv.org/4.x/da/d6e/tutorial_py_geometric_transformations.html",
        scratch="geometry.fit_homography",
    ),
    8: dict(
        overview="A color space is a coordinate system for color. RGB is convenient for displays, HSV separates hue from saturation and value, and LAB separates lightness from opponent color axes. Choosing a space can make a simple threshold useful, but it does not remove lighting variation.",
        titles=[
            "RGB, BGR and channel conventions",
            "HSV color masks and hue wraparound",
            "LAB, YCrCb and robust thresholds",
        ],
        lessons=[
            "RGB and BGR store the same three color components in different orders. Grayscale deliberately discards chromatic information. A channel is a measurement axis, not an object category. Verify the dtype-specific range whenever converting spaces; OpenCV integer encodings are not identical to textbook floating-point units.",
            "Hue cycles around a color wheel. In OpenCV 8-bit HSV, hue spans 0–179 while saturation and value span 0–255. Red straddles the hue boundary, so its mask combines two ranges. Hue becomes unstable near gray, which is why hue thresholding also needs a minimum saturation.",
            "LAB lightness and chromatic coordinates can reduce some sensitivity to brightness, and YCrCb separates luma from chroma. Neither guarantees invariance to illumination or camera processing. Skin-color masks are especially fragile across people, lighting and devices; they should not be treated as identity detectors or universal human detectors.",
        ],
        math=r"M=(h<h_1\;\lor\;h>h_2)\land(s>s_0)\land(v>v_0)",
        symbols="M is a Boolean red mask, h hue, s saturation and v value. h1 and h2 bound the two sides of red; s0 and v0 reject gray and darkness. For h=178, s=200, v=150 and bounds 10,170,80,50, the mask is true.",
        example="h, s, v = np.array([178, 30]), np.array([200, 200]), np.array([150, 150])\nmask = ((h < 10) | (h > 170)) & (s > 80) & (v > 50)\nassert mask.tolist() == [True, False]\nprint(mask)",
        internals="Convert RGB to HSV once, threshold channels, combine hue intervals and clean the binary mask using morphology. A centroid can then drive a simple color tracker.",
        experiment="Lower saturation while keeping hue fixed and observe the reliability of the red mask. Test two illuminations with the same object.",
        pitfall="Using hue degrees 0–360 directly on OpenCV uint8 HSV produces incorrect thresholds. Skin color is not a reliable substitute for a trained hand detector.",
        challenge="Track a colored ball through changing brightness, log lost detections and provide a calibration control for the color interval.",
        reference="https://docs.opencv.org/4.x/df/d9d/tutorial_py_colorspaces.html",
        scratch="numerics.components",
    ),
    9: dict(
        overview="A feature is a location with a pattern that can be found again. A uniform wall gives no precise location; a corner constrains movement in two directions. Feature detection chooses interesting points, while feature description records a neighborhood for later comparison.",
        titles=[
            "Structure tensors and Harris corners",
            "Shi–Tomasi selection and suppression",
            "FAST, scale and detector tradeoffs",
        ],
        lessons=[
            "The structure tensor summarizes products of horizontal and vertical gradients in a local window. Two small eigenvalues indicate a flat region; one large value indicates an edge; two large values indicate a corner. Harris combines determinant and trace into a score without explicitly computing both eigenvalues.",
            "Shi–Tomasi scores a point using the smaller structure-tensor eigenvalue. Good features also need spatial separation: a threshold alone may return many neighboring pixels around one physical corner. Non-maximum suppression and a minimum distance create a useful set rather than a dense blob of redundant detections.",
            "FAST compares a ring of pixels around a candidate to its center and searches for a contiguous brighter or darker arc. It is efficient but not inherently scale invariant. SIFT adds scale-space extrema and orientation; ORB combines oriented FAST with a binary descriptor. Detection repeatability and descriptor distinctiveness are different properties.",
        ],
        math=r"R=\det(M)-k\,\operatorname{trace}(M)^2",
        symbols="M is the 2×2 sum of local gradient outer products, R the Harris response and k a sensitivity parameter. For eigenvalues 4 and 3, det=12 and trace=7; with k=0.04, R=10.04.",
        example="M = np.diag([4., 3.])\nk = .04\nresponse = np.linalg.det(M) - k * np.trace(M)**2\nassert np.isclose(response, 10.04)\nprint(response)",
        internals="The reference computes Sobel gradients, smooths their products and forms the response. The library comparison applies detector-specific selection, so point sets need not be identical.",
        experiment="Rotate and blur a checkerboard. Count repeatable detections after transforming coordinates back, rather than comparing only raw detection counts.",
        pitfall="A high feature count is not proof of useful coverage. Border padding and threshold units influence the response.",
        challenge="Build a feature benchmark that measures repeatability under known rotations, scales and illumination changes.",
        reference="https://docs.opencv.org/4.x/dc/d0d/tutorial_py_features_harris.html",
        scratch="numerics.harris",
    ),
    10: dict(
        overview="A descriptor turns a neighborhood into a vector or bit string. Matching asks which vectors likely describe the same physical point. A nearest neighbor is only a proposal: geometry is needed to reject accidental visual similarities.",
        titles=[
            "Descriptors and distance metrics",
            "Ratio tests and robust correspondence",
            "RANSAC homography and stitching",
        ],
        lessons=[
            "SIFT descriptors are floating-point histograms, commonly compared with Euclidean distance. ORB descriptors are binary strings, compared with Hamming distance. BFMatcher checks descriptor pairs directly; FLANN uses approximate search structures suited to the descriptor type. A mismatch between descriptor type and distance changes the meaning of similarity.",
            "The ratio test compares the nearest match distance with the second nearest. A ratio near one means the best candidate is ambiguous. Cross-checking asks whether the match is mutual; it is a different filter. Neither resolves repeated texture or guarantees a correct correspondence.",
            "RANSAC repeatedly samples a minimal set, fits a model and counts points whose reprojection error is small. The best consensus is refined using inliers. For stitching a mostly planar scene or pure camera rotation, a homography can align overlapping images; blending, exposure and parallax still require attention.",
        ],
        math=r"d_1/d_2<\tau",
        symbols="d1 is the nearest descriptor distance, d2 the second nearest and τ the chosen ratio threshold. Distances 12 and 30 produce 0.4 and pass τ=0.75. Zero second-neighbor distance is ambiguous and should not be divided blindly.",
        example="best, second, ratio_threshold = 12., 30., .75\naccepted = second > 0 and best / second < ratio_threshold\nassert accepted\nprint(accepted)",
        internals="The lab detects ORB or SIFT features in a generated texture and its translated view, filters matches, estimates a RANSAC homography and compares translation with known truth.",
        experiment="Add repeated tiles and increase viewpoint change. Record keypoints, accepted matches, inliers and reprojection error separately.",
        pitfall="Drawing many lines between two images can conceal false correspondences. A low residual on a tiny cluster of points may extrapolate badly.",
        challenge="Build a two-image stitcher that refuses weak geometry, reports inlier coverage and blends only a valid overlap.",
        reference="https://docs.opencv.org/4.x/dc/dc3/tutorial_py_matcher.html",
        scratch="geometry.fit_homography",
    ),
    11: dict(
        overview="Morphology processes shape using a small structuring element. Imagine moving a stencil across a binary mask and asking whether any or all covered pixels are foreground. This provides controllable ways to remove specks, fill gaps and outline regions.",
        titles=[
            "Erosion and dilation from scratch",
            "Opening and closing",
            "Gradients, top-hat and black-hat",
        ],
        lessons=[
            "Binary erosion keeps a pixel only when every active stencil position fits inside foreground. Dilation keeps it when any stencil position touches foreground. A disk, square and line encode different geometric assumptions. This lab uses a full square stencil and treats pixels outside the image as background.",
            "Opening is erosion followed by dilation; it removes small foreground structures. Closing reverses the order and can fill narrow background gaps. Applying an operation repeatedly changes the effective scale. These operations alter measurements, so cleaning a mask before area estimation needs a documented policy.",
            "The morphological gradient subtracts erosion from dilation to highlight boundaries. Top-hat subtracts an opening from the original to reveal small bright structures; black-hat subtracts the original from a closing to reveal small dark structures. Grayscale morphology uses neighborhood minima and maxima instead of Boolean all/any.",
        ],
        math=r"(A\ominus B)(p)=\bigwedge_{b\in B}A(p+b)",
        symbols="A is a Boolean image, B the active stencil offsets, p the current pixel, and ∧ means all entries must be true. For a 3×3 all-foreground patch, erosion returns true; one missing entry makes it false.",
        example="patch = np.ones((3, 3), dtype=bool)\nassert patch.all()\npatch[0, 0] = False\neroded_center = patch.all()\ndilated_center = patch.any()\nprint(eroded_center, dilated_center)",
        internals="The reference pads with false, scans square windows and evaluates all or any. OpenCV performs optimized morphology; border settings must match to compare edges.",
        experiment="Try a horizontal line stencil on broken text and compare it with a square stencil. Measure whether neighboring letters incorrectly merge.",
        pitfall="Opening can delete legitimate thin lines. The structuring element size should reflect object scale, not an arbitrary constant copied from another image.",
        challenge="Create a document cleanup pipeline that removes isolated noise while preserving narrow strokes, with before/after component statistics.",
        reference="https://docs.opencv.org/4.x/d9/d61/tutorial_py_morphological_ops.html",
        scratch="numerics.morphology",
    ),
    12: dict(
        overview="A contour traces a region boundary. Once a segmentation mask is available, contours convert pixels into geometric measurements: area, perimeter, enclosing boxes, convex hulls and polygon approximations. The measurement is only as reliable as the mask and scale calibration.",
        titles=[
            "Contours, components and measurements",
            "Bounding rectangles and shape approximations",
            "Convexity and calibrated dimensions",
        ],
        lessons=[
            "Connected components label foreground regions; contours trace their boundaries. They answer related but different questions. A contour polygon area differs from counting foreground pixel centers, especially for small objects. Retrieval mode controls whether holes and nested boundaries are returned.",
            "An axis-aligned bounding box follows image axes; a rotated minimum-area rectangle follows object orientation. Polygon approximation removes points while limiting boundary deviation. Too large an epsilon turns curved shapes into crude polygons, while too small an epsilon preserves noise.",
            "A convex hull encloses a contour without inward dents. Solidity compares region area with hull area; circularity compares area and perimeter. These are descriptors, not universal category rules. Converting pixels to millimeters requires known scale or camera geometry and an assumption about the measurement plane.",
        ],
        math=r"C=4\pi A/P^2",
        symbols="C is circularity, A region area and P perimeter in consistent units. A continuous circle of radius 3 has area 9π and perimeter 6π, yielding C=1. Digitized contours generally differ from the continuous ideal.",
        example="radius = 3.\narea = np.pi * radius**2\nperimeter = 2 * np.pi * radius\ncircularity = 4 * np.pi * area / perimeter**2\nassert np.isclose(circularity, 1)\nprint(circularity)",
        internals="OpenCV finds boundaries in the synthetic mask, measures each contour and overlays approximations and rotated boxes. Shape rules use measured values and expose ambiguous cases.",
        experiment="Rotate a rectangle and compare its axis-aligned box area with its minimum-area box. Add holes and inspect contour hierarchy.",
        pitfall="Perspective changes apparent size. A fixed pixels-per-millimeter ratio cannot measure arbitrary depths.",
        challenge="Build a shape measurement tool using a reference object on the same plane, and include uncertainty from boundary perturbations.",
        reference="https://docs.opencv.org/4.x/d3/d05/tutorial_py_table_of_contents_contours.html",
        scratch="numerics.components",
    ),
    13: dict(
        overview="Edges are rapid changes in image intensity. They often correspond to boundaries, but also arise from texture, shadows and noise. A derivative measures change; a good edge pipeline controls noise and decides which changes should form connected boundaries.",
        titles=[
            "Gradients, Sobel and Scharr",
            "Laplacian and second derivatives",
            "Canny step by step",
        ],
        lessons=[
            "A horizontal derivative responds to left-right intensity change, and a vertical derivative responds to up-down change. Sobel combines differencing with smoothing. Scharr uses different coefficients to improve rotational behavior for small kernels. Gradient magnitude combines both responses; orientation is obtained with atan2.",
            "The Laplacian adds second derivatives and responds to changes in the gradient. It can highlight fine structures but amplifies noise strongly. A signed or floating representation is essential: clipping negative derivatives to zero destroys half the signal. Absolute value is a display choice, not the derivative itself.",
            "Canny smooths the image, estimates gradients, thins responses through non-maximum suppression, applies high and low thresholds, and keeps weak edges connected to strong ones through hysteresis. The reference uses four orientation bins and relative thresholds; OpenCV has different implementation details and absolute thresholds, so exact edge maps are not expected.",
        ],
        math=r"G=\sqrt{G_x^2+G_y^2},\qquad\theta=\operatorname{atan2}(G_y,G_x)",
        symbols="Gx and Gy are horizontal and vertical derivatives, G their magnitude and θ edge-normal orientation. Derivatives (3,4) have magnitude 5 and orientation about 53.13 degrees.",
        example="gx, gy = 3., 4.\nmagnitude = np.hypot(gx, gy)\norientation = np.degrees(np.arctan2(gy, gx))\nassert magnitude == 5\nprint(magnitude, orientation)",
        internals="Follow the NumPy implementation in order: Gaussian blur → Sobel → magnitude/orientation → directional suppression → two thresholds → queue-based hysteresis. Compare intermediate arrays, not only the final binary output.",
        experiment="Increase noise and independently change blur scale and hysteresis thresholds. Observe missing boundaries versus false texture edges.",
        pitfall="Edges are not closed object masks. Applying contours to a broken Canny map can produce fragmented shapes.",
        challenge="Detect a document boundary from gradients, reject implausible quadrilaterals, and rectify the highest-quality candidate.",
        reference="https://docs.opencv.org/4.x/da/d22/tutorial_py_canny.html",
        scratch="numerics.canny_reference",
    ),
    14: dict(
        overview="Segmentation assigns a label to each pixel. Classical methods use explicit assumptions about intensity, color or connectivity. They are useful baselines because their failure conditions are easier to inspect than those of a large trained model.",
        titles=[
            "Global, adaptive and Otsu thresholds",
            "K-means color segmentation",
            "Connected components and region cleanup",
        ],
        lessons=[
            "A threshold separates pixels above and below a cutoff. Otsu chooses a cutoff by maximizing between-class variance in the histogram. It works best when two intensity groups are meaningfully separable. Adaptive thresholding computes local cutoffs and can handle uneven illumination, but its neighborhood size introduces another scale assumption.",
            "K-means alternates assigning each feature vector to its nearest center and recomputing centers as means. For color segmentation, each pixel is a point in a color space. Cluster IDs have no semantic meaning and may permute between runs. Adding coordinates favors spatial compactness but changes the distance metric.",
            "Connected-component labeling groups adjacent foreground pixels after thresholding. Four-connectivity joins horizontal and vertical neighbors; eight-connectivity also joins diagonals. Component size filters remove specks but may remove real small objects. Compare the full pipeline against a known mask using IoU rather than visual impression alone.",
        ],
        math=r"J=\sum_i\lVert x_i-\mu_{c_i}\rVert^2",
        symbols="xi is a pixel feature vector, ci its cluster assignment and μ the selected cluster center. For values [1,2] assigned to center 1.5, the summed squared distance is 0.5. K-means decreases this objective but may reach a local solution.",
        example="values = np.array([1., 2.])\ncenter = values.mean()\nobjective = ((values - center)**2).sum()\nassert np.isclose(objective, .5)\nprint(center, objective)",
        internals="The Otsu reference sweeps histogram partitions, k-means updates assignments and means, and the component reference uses a queue to flood each unvisited foreground region.",
        experiment="Add a lighting gradient before thresholding. Compare Otsu and adaptive masks at fixed object geometry, then inspect component counts.",
        pitfall="Cluster zero is not automatically background. Accuracy on a mostly-background image can be high for an empty prediction.",
        challenge="Segment manufactured parts under uneven illumination and choose a thresholding or clustering method using a held-out set.",
        reference="https://docs.opencv.org/4.x/d7/d4d/tutorial_py_thresholding.html",
        scratch="numerics.kmeans",
    ),
    15: dict(
        overview="A video is a time-ordered sequence of images with timing and encoding information. Frame count, nominal FPS, processing throughput and end-to-end latency describe different things. A reliable loop must handle end-of-file, decode failures and unavailable cameras.",
        titles=[
            "Frames, codecs and video I/O",
            "Processing loops and timestamps",
            "Background models and streaming design",
        ],
        lessons=[
            "Video containers hold encoded frames and timing metadata; a codec compresses the frames. VideoWriter needs a compatible codec, frame dimensions, color convention and nominal FPS. The lab writes a small generated motion sequence, reads it back and verifies the decoded frame count. Codec availability can differ across operating systems.",
            "Each successful read produces a frame that can be preprocessed, analyzed and displayed or saved. Use actual timestamps for motion and frame age. Nominal source FPS is not a measured inference rate. Always release captures and writers, even if processing raises an error.",
            "A background model estimates what normally occupies each pixel. Subtracting it highlights changes, but shadows, camera movement and moving foliage also produce changes. For live systems, a bounded queue can prevent old frames from accumulating when processing is slower than capture. Later tracking chapters add temporal identity.",
        ],
        math=r"t_i=i/f",
        symbols="ti is the nominal timestamp of frame index i and f the constant frame rate in frames per second. Frame 45 at 30 FPS is at 1.5 seconds. Variable-frame-rate video requires actual timestamps rather than this formula.",
        example="frame_index, fps = 45, 30.\ntime_seconds = frame_index / fps\nassert np.isclose(time_seconds, 1.5)\nprint(time_seconds)",
        internals="Generated moving frames isolate codec and loop behavior from camera hardware. Differences are computed in a signed type; thresholded differences are only motion candidates.",
        experiment="Process every second frame and compare trajectory displacement per processed frame with displacement per second.",
        pitfall="VideoCapture.read returning false can mean end-of-stream or failure. Writing frames of the wrong shape may silently produce a broken video.",
        challenge="Build a video effects tool with configurable output FPS, verified frame dimensions and a useful error when the source cannot open.",
        reference="https://docs.opencv.org/4.x/dd/d43/tutorial_py_video_display.html",
        scratch="numerics.gray",
    ),
    16: dict(
        overview="Calibration estimates how a camera maps three-dimensional points to image pixels. Intrinsics describe the camera coordinate system and pixel scaling; extrinsics describe camera pose relative to a world frame. Lens distortion adds departures from the ideal pinhole model.",
        titles=[
            "Pinhole cameras and intrinsics",
            "Chessboard calibration and reprojection",
            "Distortion, undistortion and validation",
        ],
        lessons=[
            "The intrinsic matrix contains horizontal and vertical focal lengths in pixels and the principal point. Rotation and translation place a world point in camera coordinates. Perspective division makes distant objects appear smaller. Physical focal length in millimeters cannot be substituted for focal length in pixels without sensor scaling.",
            "A calibration board supplies known points in a plane. Observe it at varied angles and positions, detect corners and minimize reprojection error across views. Reprojection error measures agreement with detected image points; it does not by itself guarantee accurate depth. The lab uses known synthetic board poses and compares recovered parameters with truth.",
            "Radial distortion bends lines increasingly away from the optical center, while tangential terms model decentering effects. Undistortion remaps pixels and can leave empty borders. A calibration depends on image resolution, focus and lens configuration. Reserve independent board views for evaluation and inspect spatial residual patterns.",
        ],
        math=r"u=f_xX/Z+c_x,\qquad v=f_yY/Z+c_y",
        symbols="X,Y,Z are camera-frame coordinates, fx,fy focal lengths in pixels, and cx,cy principal point. With X=0.2 m, Z=2 m, fx=400 px and cx=320 px, u=360 px.",
        example="X, Z, fx, cx = .2, 2., 400., 320.\nu = fx * X / Z + cx\nassert np.isclose(u, 360)\nprint(u)",
        internals="The synthetic lab projects a grid through known intrinsics and poses, adds pixel noise and calls calibrateCamera. The reported parameter error is meaningful because synthetic truth is available.",
        experiment="Use many nearly identical front-facing board views versus varied views. Compare parameter stability, not just training reprojection error.",
        pitfall="Chessboard dimensions count inner corners, not squares. Mixing units changes estimated translations and baseline scale.",
        challenge="Build a calibration toolkit that saves K, distortion, image size, board units and per-view errors, and rejects an empty detection set.",
        reference="https://docs.opencv.org/4.x/dc/dbb/tutorial_py_calibration.html",
        scratch="geometry.project",
    ),
    17: dict(
        overview="Motion detection asks where the scene changes over time. It does not identify object categories or preserve identity. The simplest useful systems compare frames or maintain a slowly changing background and then clean a foreground mask.",
        titles=[
            "Frame differencing",
            "Running backgrounds and adaptation",
            "MOG2, shadows and failure analysis",
        ],
        lessons=[
            "Frame differencing subtracts consecutive images and thresholds the absolute change. It emphasizes movement boundaries and can miss the interior of a slowly moving object. A stopped object disappears from the difference even though it still occupies the scene.",
            "An exponential running average updates each background pixel with a weighted portion of the current frame. A large update rate adapts quickly but absorbs stopped objects; a small rate keeps old conditions longer. Updating only likely background regions can reduce contamination, but classification errors can then freeze the model.",
            "MOG2 models a pixel with a mixture of distributions to handle some recurring background variations. Shadows may receive a distinct mask value. A moving camera changes almost every pixel, so stabilization or camera-motion estimation is needed before interpreting foreground as object motion.",
        ],
        math=r"B_t=(1-\alpha)B_{t-1}+\alpha I_t",
        symbols="Bt is the updated background, It the current frame and α the update rate. For previous background 100, current intensity 140 and α=0.1, the new estimate is 104.",
        example="previous, current, alpha = 100., 140., .1\nbackground = (1 - alpha) * previous + alpha * current\nassert np.isclose(background, 104)\nprint(background)",
        internals="The generated sequence supplies an initial background and moving foreground. The lab compares absolute differences, a running mean and OpenCV MOG2 masks under a fixed seed.",
        experiment="Stop the object midway and vary adaptation rate. Measure how long it remains foreground and how long a ghost remains after it leaves.",
        pitfall="Global lighting changes resemble motion. A binary foreground mask does not distinguish one object from two touching objects.",
        challenge="Design a motion-triggered recorder with warm-up, hysteresis and an explicit false-trigger test under lighting changes.",
        reference="https://docs.opencv.org/4.x/d1/dc5/tutorial_background_subtraction.html",
        scratch="tracking.KalmanTracker",
    ),
    18: dict(
        overview="Tracking estimates an object state over time. Detection supplies observations; a motion model predicts where the object might be next. Keeping uncertainty explicit allows a tracker to bridge short missing detections without pretending its prediction is a measurement.",
        titles=[
            "State, observations and prediction",
            "Kalman correction and uncertainty",
            "Occlusion, gating and track lifetime",
        ],
        lessons=[
            "A simple state stores x, y, horizontal velocity and vertical velocity. A constant-velocity transition advances position by velocity times elapsed time. Process noise represents unmodeled acceleration. A detection observes position with measurement noise and usually does not directly observe velocity.",
            "Kalman correction combines prediction and measurement using their uncertainties. The gain is larger when the prediction is uncertain and smaller when the measurement is noisy. Covariance tracks uncertainty, including relationships between position and velocity. The implementation uses a numerically stable covariance update.",
            "Gating rejects observations too far from a predicted state. During a missing detection, a track predicts forward and its uncertainty grows. A maximum missed-frame policy eventually deletes it. Template-based trackers such as correlation filters and detector-assisted tracking use different observations; neither guarantees identity through long occlusion.",
        ],
        math=r"x_{t+1}=x_t+v_x\Delta t",
        symbols="x is horizontal position, vx horizontal velocity and Δt elapsed time. At x=10 px, velocity 3 px/s and Δt=0.5 s, predicted x is 11.5 px. This model assumes constant velocity over that interval.",
        example="position, velocity, dt = 10., 3., .5\nprediction = position + velocity * dt\nassert np.isclose(prediction, 11.5)\nprint(prediction)",
        internals="The tracker predicts state/covariance, associates gated observations, corrects matched tracks and expires stale tracks. The lab compares noisy centers and filtered positions against known trajectories.",
        experiment="Increase measurement noise and insert a short occlusion. Plot position error and inspect uncertainty rather than judging smoothness alone.",
        pitfall="A smooth trajectory can still be wrong. Pixel velocity changes when FPS changes unless elapsed time is included.",
        challenge="Track a ball with a detector and motion model, report lost periods, and distinguish observed positions from predictions.",
        reference="https://docs.opencv.org/4.x/dd/d6a/classcv_1_1KalmanFilter.html",
        scratch="tracking.KalmanTracker",
    ),
}
