"""Authored lessons for transformers, generative vision, 3D and production systems."""

CONTENT = {
    37: dict(
        overview="A Vision Transformer turns an image into a sequence of patch tokens and lets tokens exchange information through attention. This changes the inductive assumptions used by a CNN. Read the attention primer in Chapter 38 before implementing the transformer block here; the directory numbering follows the requested catalog.",
        titles=[
            "Patch embeddings and positions",
            "Transformer encoder mechanics",
            "Train a simplified ViT",
        ],
        lessons=[
            "Divide an image into non-overlapping patches, flatten each patch and project it into an embedding vector. A convolution with kernel and stride equal to the patch size performs the same shared projection. Position embeddings distinguish where tokens came from; otherwise attention alone does not encode the image grid order.",
            "An encoder block combines self-attention, a token-wise feed-forward network, normalization and residual connections. Queries compare each token with keys, and the resulting weights mix values. Multiple heads learn different projections. The local model uses one small encoder and mean pooling rather than reproducing a large published checkpoint.",
            "Train the tiny model on generated shapes, compare patch size and inspect held-out predictions. Small data can favor stronger locality assumptions. A pretrained ViT can be run through the optional torchvision classifier workflow, but downloading weights and evaluating on a real dataset are separate explicit steps.",
        ],
        math=r"N=(H/P)(W/P)",
        symbols="H and W are image height and width, P square patch size and N the number of patch tokens when dimensions divide exactly. A 24×24 image with 6×6 patches produces 16 tokens.",
        example="height, width, patch = 24, 24, 6\nassert height % patch == width % patch == 0\ntokens = (height // patch) * (width // patch)\nassert tokens == 16\nprint(tokens)",
        internals="TinyViT uses a patch projection, learned position embeddings, an encoder block, normalization, token averaging and a classifier. The source exposes each step instead of calling a pretrained model in the default notebook.",
        experiment="Double the number of tokens and estimate attention-matrix growth before measuring memory. Compare the tiny CNN and ViT on the same synthetic split.",
        pitfall="Reshape cannot replace a correct patch permutation. Pretrained position embeddings may need resizing when image resolution changes.",
        challenge="Compare a small CNN and ViT under equal training budgets, with fixed splits and ablations for patch size and position embeddings.",
        reference="https://arxiv.org/abs/2010.11929",
        scratch="models.TinyViT",
    ),
    38: dict(
        overview="Attention is a data-dependent weighted average. Imagine asking a question of every item, scoring how relevant each item is, and combining the information from the most relevant items. Queries, keys and values are learned projections that make this comparison trainable.",
        titles=[
            "Queries, keys and values",
            "Scaled dot-product attention",
            "Masks, heads and efficient attention",
        ],
        lessons=[
            "A query represents what a token seeks, a key represents how a token can be matched, and a value carries the information to combine. In self-attention all three come from the same sequence; in cross-attention queries and key/value tokens come from different sources. These are mathematical roles, not literal language questions.",
            "Multiply queries by transposed keys to form a score matrix, divide by the square root of key dimension, apply a row-wise softmax and multiply by values. Scaling controls score magnitude as dimension grows. The NumPy implementation uses stable softmax and is compared numerically with PyTorch.",
            "A mask blocks disallowed token pairs before normalization. A causal mask prevents access to future tokens, whereas image classification usually allows all patches to interact. Multiple heads use distinct projections. Full attention stores token-pair relationships, which grows quadratically with token count; optimized kernels reduce memory traffic but do not make every formulation linear.",
        ],
        math=r"Attention(Q,K,V)=softmax(QK^T/\sqrt{d_k})V",
        symbols="Q and K are query/key matrices, V contains values and dk is key width. Softmax acts over keys for each query. Equal scores over two values [2,6] yield their mean 4.",
        example="scores = np.array([0., 0.])\nweights = np.exp(scores) / np.exp(scores).sum()\nvalues = np.array([2., 6.])\noutput = weights @ values\nassert np.isclose(output, 4)\nprint(weights, output)",
        internals="The reference returns both weighted values and the attention matrix, allowing row sums and masked entries to be inspected. Framework comparison uses matching inputs and mask conventions.",
        experiment="Scale query/key magnitudes and inspect whether attention becomes peaked. Apply a triangular mask and verify forbidden weights are zero.",
        pitfall="A softmax over the wrong axis can still produce plausible array shapes. Attention weights are not automatically causal explanations of predictions.",
        challenge="Implement multi-head attention by splitting and recombining dimensions, then compare outputs and gradients with a library module.",
        reference="https://arxiv.org/abs/1706.03762",
        scratch="numerics.attention",
    ),
    39: dict(
        overview="Self-supervised learning constructs a training signal from data itself. The goal is a useful representation, not merely a low pretext-task loss. Augmentations and objectives decide what information is preserved and what is deliberately ignored.",
        titles=[
            "Contrastive views and SimCLR",
            "EMA targets and BYOL ideas",
            "Masked image modeling and evaluation",
        ],
        lessons=[
            "Contrastive learning pulls representations of two augmented views of the same image together and distinguishes other examples. Normalization and temperature control similarity scores. The local SimCLR-style experiment forms paired views and computes a normalized temperature-scaled contrastive objective. Augmentations must preserve information needed for downstream tasks.",
            "BYOL uses an online network, predictor, target network and stop-gradient, with the target updated through an exponential moving average. These details interact in preventing trivial collapse. The local EMA consistency lab isolates target updates and intentionally omits parts of full BYOL; its loss is not evidence that a faithful BYOL reproduction has been achieved.",
            "Masked image modeling hides part of an input and learns to reconstruct missing content. Pixel reconstruction can encourage local appearance knowledge but is not identical to semantic understanding. Evaluate representations with a frozen linear probe or controlled fine-tuning on a separate labeled split, rather than judging only reconstruction loss.",
        ],
        math=r"\theta_{target}\leftarrow m\theta_{target}+(1-m)\theta_{online}",
        symbols="m is the EMA momentum, θtarget the slow-moving parameters and θonline the current trained parameters. With values 1 and 3 and m=0.9, the target becomes 1.2.",
        example="target, online, momentum = 1., 3., .9\nupdated_target = momentum * target + (1 - momentum) * online\nassert np.isclose(updated_target, 1.2)\nprint(updated_target)",
        internals="Three experiments isolate contrastive pair construction, EMA target consistency and masked reconstruction. They use small synthetic data and report local objectives, not large-scale representation benchmarks.",
        experiment="Remove an augmentation and measure downstream probe performance, not only training loss. Check embedding variance for collapse.",
        pitfall="Two crops can remove the object and cease to be meaningful positive pairs. EMA consistency without the full method can collapse.",
        challenge="Pretrain a representation without labels and compare a frozen linear probe with a randomly initialized baseline on identical labeled splits.",
        reference="https://arxiv.org/abs/2002.05709",
        scratch="models.Autoencoder",
    ),
    40: dict(
        overview="Vision-language models relate images to text. A dual encoder can compare image and text embeddings for retrieval; a generative model can produce captions or answers. These are different capabilities and require different outputs and evaluation.",
        titles=[
            "Image–text embedding alignment",
            "Retrieval and zero-shot candidate scoring",
            "Captioning, VQA and grounding limits",
        ],
        lessons=[
            "An image encoder and text encoder map their inputs into a shared space. Training can increase similarity for paired observations and reduce it for other pairs. The CPU lab learns three synthetic word embeddings and a small image encoder; it demonstrates alignment but has no open-vocabulary language understanding.",
            "CLIP-style inference compares an image with candidate text prompts. Softmax scores are relative to the chosen candidates, so adding or rewording labels can change them. Prompt sensitivity and dataset shift require evaluation. The external adapter supports a real pretrained CLIP model through explicit weight-download permission in the command.",
            "Captioning generates a description, while visual question answering conditions on both an image and a question. Generation can add details unsupported by the image. The optional BLIP adapters demonstrate these tasks, but factual grounding, sensitive data handling and downstream verification remain the application’s responsibility.",
        ],
        math=r"s_{ij}=\hat v_i^T\hat t_j/\tau",
        symbols="Normalized image embedding v̂i and text embedding t̂j have dot-product similarity, scaled by positive temperature τ. Aligned unit vectors have similarity 1 before scaling. These scores are not calibrated truth probabilities.",
        example="image_embedding = np.array([1., 0.])\ntext_embeddings = np.array([[1., 0.], [0., 1.]])\nscores = text_embeddings @ image_embedding\nassert np.allclose(scores, [1., 0.])\nprint(scores)",
        internals="The local dual encoder learns a closed vocabulary on generated image-label pairs. Pretrained retrieval, captioning and VQA are implemented separately and are never silently substituted for this small experiment.",
        experiment="Add a visually similar distractor prompt to a candidate set and inspect score changes. Evaluate retrieval rank rather than assuming a fixed probability meaning.",
        pitfall="A plausible caption may hallucinate objects. An embedding similarity cannot establish a person’s identity, intent or protected traits.",
        challenge="Build an image search tool with a documented candidate set, retrieval metrics and an error gallery for ambiguous prompts.",
        reference="https://arxiv.org/abs/2103.00020",
        scratch="numerics.attention",
    ),
    41: dict(
        overview="Multimodal vision combines information from different sources, such as RGB, depth, text or audio. The central problems include alignment, missing inputs and conflicting evidence. More sensors can improve a system only when their uncertainties and timing are handled correctly.",
        titles=[
            "Early, late and cross-modal fusion",
            "Uncertainty-weighted sensor fusion",
            "Missing modalities and synchronization",
        ],
        lessons=[
            "Early fusion combines inputs or features before the final predictor; late fusion combines separate predictions. Cross-attention can allow one modality to query another. These choices trade flexibility, missing-input handling and compute. RGB and depth must refer to compatible coordinates before pixel-level fusion makes sense.",
            "When two independent Gaussian measurements estimate the same quantity, weighting by inverse variance gives a minimum-variance combination. The scalar lab uses known synthetic noise to demonstrate this rule. Real uncertainty must be estimated and checked; correlated errors violate the independence assumption.",
            "A missing modality should trigger an explicit fallback, not a fabricated zero measurement. Timestamp misalignment can turn useful depth or audio into contradictory evidence. Evaluate performance with dropped, delayed and corrupted modalities so the system does not rely silently on ideal sensor availability.",
        ],
        math=r"\hat x=(x_1/\sigma_1^2+x_2/\sigma_2^2)/(1/\sigma_1^2+1/\sigma_2^2)",
        symbols="x1,x2 estimate one quantity and σ1²,σ2² are independent measurement variances. Measurements 2 and 4 with variances 1 and 4 combine to 2.4, closer to the more precise first sensor.",
        example="x1, x2, variance1, variance2 = 2., 4., 1., 4.\nfused = (x1/variance1 + x2/variance2) / (1/variance1 + 1/variance2)\nassert np.isclose(fused, 2.4)\nprint(fused)",
        internals="The lab generates visual and depth-like scalar measurements, applies precision weighting and falls back to the available sensor when depth is missing. It isolates fusion rather than a full learned multimodal architecture.",
        experiment="Make sensor errors correlated and compare the theoretical confidence with observed error. Then introduce missing depth.",
        pitfall="Concatenating arrays is not sufficient if modalities describe different times or coordinates. A high-confidence sensor can still be systematically biased.",
        challenge="Design an RGB-depth inspection pipeline that detects stale measurements and evaluates with one sensor disabled.",
        reference="https://docs.opencv.org/4.x/d9/d0c/group__calib3d.html",
        scratch="numerics.softmax",
    ),
    42: dict(
        overview="Generative vision learns to reconstruct or synthesize images. An autoencoder compresses observations, a VAE imposes a probabilistic latent structure, and a GAN learns through competition. Understanding their objectives helps explain blur, collapse and unstable training.",
        titles=[
            "Autoencoders and reconstruction",
            "Variational autoencoders",
            "GAN objectives and failure analysis",
        ],
        lessons=[
            "An encoder maps an image into a smaller latent representation and a decoder reconstructs it. A reconstruction objective rewards recovering input pixels but does not automatically organize the latent space for random sampling. A model can memorize examples, so held-out reconstruction and interpolation need separate inspection.",
            "A VAE predicts a latent mean and variance and samples using a differentiable reparameterization. Its objective balances reconstruction with a KL penalty toward a prior. Increasing the regularization can improve latent structure while reducing sharpness. The tiny lab uses an MLP VAE on generated shapes.",
            "A GAN trains a generator to create images and a discriminator to distinguish real from generated images. Their changing objectives make optimization a game rather than ordinary supervised fitting. Mode collapse can produce a few plausible images while ignoring diversity. Short CPU training runs illustrate mechanics and may produce poor samples.",
        ],
        math=r"z=\mu+\sigma\odot\epsilon,\qquad\epsilon\sim\mathcal N(0,I)",
        symbols="μ and σ are encoder outputs, ε standard-normal noise, ⊙ elementwise multiplication and z the sampled latent vector. With μ=2, σ=0.5 and ε=−1, z=1.5. Gradients can pass through μ and σ.",
        example="mean, standard_deviation, noise = 2., .5, -1.\nlatent = mean + standard_deviation * noise\nassert np.isclose(latent, 1.5)\nprint(latent)",
        internals="The three local modes train an autoencoder, VAE or small GAN and display their actual outputs. Loss curves are optimization observations, not substitutes for diversity or realism evaluation.",
        experiment="Interpolate between two latent codes, vary the VAE KL weight and inspect whether the GAN repeats a few outputs.",
        pitfall="Low reconstruction MSE can favor blurry averages. Cherry-picked generated samples do not establish model quality.",
        challenge="Compare reconstruction quality and sample diversity of an AE, VAE and GAN under a documented compute budget.",
        reference="https://arxiv.org/abs/1312.6114",
        scratch="models.Autoencoder",
    ),
    43: dict(
        overview="Diffusion models learn to reverse a gradual noising process. The forward process is prescribed, while a network learns a reverse-step ingredient such as noise prediction. Sampling repeats many learned denoising steps, making the noise schedule and parameterization essential.",
        titles=[
            "Forward noising schedules",
            "Noise prediction and training",
            "Reverse sampling and conditioning",
        ],
        lessons=[
            "At each forward step, a small amount of Gaussian noise replaces signal. Products of retained signal fractions allow sampling a noisy image at any time directly. Early times preserve much of the image; late times approach noise. A short schedule may not fully erase the training image, which affects sampling assumptions.",
            "A noise-prediction network sees the noisy image and time index and predicts the injected noise. Mean squared error supplies a simple training objective. Time conditioning tells the network which noise level it is solving. The local model is a small MLP trained on 16×16 generated shapes.",
            "Reverse sampling starts from noise and repeatedly estimates a cleaner state while adding schedule-dependent randomness. Guidance and image-to-image methods introduce additional conditioning and strength controls. The lab implements a small DDPM-style sampler; it is not a pretrained text-to-image system, and its short runs are expected to be low quality.",
        ],
        math=r"x_t=\sqrt{\bar\alpha_t}x_0+\sqrt{1-\bar\alpha_t}\epsilon",
        symbols="x0 is clean data, ε standard-normal noise, ᾱt cumulative signal retention and xt the noisy sample. With ᾱ=0.64, x0=1 and ε=0, xt=0.8. The two square-root factors control signal and noise variance.",
        example="alpha_bar, clean, noise = .64, 1., 0.\nnoisy = np.sqrt(alpha_bar)*clean + np.sqrt(1-alpha_bar)*noise\nassert np.isclose(noisy, .8)\nprint(noisy)",
        internals="The source samples random time indices, creates noisy inputs with known noise targets, optimizes an MSE objective and executes a reverse loop. Training and sampling use the same stored schedule.",
        experiment="Plot signal retention across steps and compare samples after different training budgets. Check that the final forward state is close to the assumed starting distribution.",
        pitfall="Confusing predicted noise with a predicted clean image changes the reverse equation. A falling noise loss is not a guarantee of visually good samples.",
        challenge="Implement a conditional shape diffusion model and evaluate whether conditioning changes both class fidelity and sample diversity.",
        reference="https://arxiv.org/abs/2006.11239",
        scratch="models.diffusion_train_sample",
    ),
    44: dict(
        overview="Three-dimensional vision connects world geometry to image measurements. A single image loses depth through projection; multiple views and assumptions can constrain it. Coordinate frames, units and calibration are as important as the reconstruction algorithm.",
        titles=[
            "World, camera and image coordinates",
            "Epipolar geometry and triangulation",
            "Reprojection and reconstruction error",
        ],
        lessons=[
            "A rigid pose uses a rotation matrix and translation to map coordinates between frames. Rotation preserves lengths and has determinant +1. The camera projects camera-frame XYZ through intrinsics and perspective division. Be explicit whether a transform maps world to camera or camera to world; their translations are not interchangeable.",
            "Corresponding points lie on related epipolar lines. A fundamental matrix describes the pixel-coordinate constraint; an essential matrix describes calibrated rays. Triangulation finds a 3D point consistent with two camera projections. The lab assumes known calibration and correspondences so that this geometric step can be studied independently.",
            "Reprojection error compares predicted and observed pixels, whereas 3D error compares reconstructed and true world coordinates. Small ray intersection angles make depth uncertain even with modest pixel residuals. Real reconstruction also needs feature matching, pose estimation, outlier rejection and often bundle adjustment.",
        ],
        math=r"\tilde p\sim K[R\mid t]\tilde X",
        symbols="X̃ is a homogeneous world point, R,t map world to camera, K contains intrinsics and p̃ is homogeneous image position. The symbol ∼ means equal up to a nonzero scale. Dividing by depth yields pixel coordinates.",
        example="world = np.array([1., 2., 4., 1.])\nprojection = np.column_stack([np.eye(3), np.zeros(3)])\nq = projection @ world\npixel = q[:2] / q[2]\nassert np.allclose(pixel, [.25, .5])\nprint(pixel)",
        internals="The reference builds four linear equations per correspondence and solves a homogeneous least-squares problem by SVD. OpenCV triangulation is compared under identical camera matrices.",
        experiment="Reduce the baseline while holding pixel noise fixed and measure how 3D error changes. Include points at several depths.",
        pitfall="Low reprojection error alone does not fix scale or guarantee accurate depth. Mixing left-handed and right-handed frames can mirror a reconstruction.",
        challenge="Reconstruct a calibrated synthetic scene, then replace known correspondences with feature matches and quantify the new failure modes.",
        reference="https://docs.opencv.org/4.x/d9/d0c/group__calib3d.html",
        scratch="geometry.triangulate",
    ),
    45: dict(
        overview="Depth is distance along a stated camera axis or ray; the convention must be declared. Stereo geometry can recover metric depth from calibration, while monocular learned depth often has scale ambiguity or domain-dependent calibration.",
        titles=[
            "Disparity and metric depth",
            "Depth uncertainty and invalid pixels",
            "Monocular priors and evaluation",
        ],
        lessons=[
            "In a rectified stereo pair, disparity is the horizontal pixel difference between matching points. Larger disparity usually means smaller depth. Focal length in pixels and baseline in physical units determine metric scale. Zero or negative disparity should be marked invalid, not converted into an invented finite distance.",
            "Depth varies inversely with disparity, so the same pixel disparity error causes greater depth error for distant objects. First-order uncertainty propagates through the derivative of the depth formula. Evaluate only valid regions and report their coverage; excluding difficult pixels without reporting coverage can inflate apparent quality.",
            "Monocular models infer depth using learned visual priors, which can fail on unfamiliar materials, scales and camera settings. Relative depth order is different from metric depth. Aligning predicted scale on test ground truth changes the evaluation task and must be reported explicitly.",
        ],
        math=r"Z=fB/d",
        symbols="Z is depth, f focal length in pixels, B baseline in meters and d disparity in pixels. With f=200 px, B=0.12 m and d=8 px, Z=3 m. Units cancel only when f and d share pixel units.",
        example="focal_px, baseline_m, disparity_px = 200., .12, 8.\ndepth_m = focal_px * baseline_m / disparity_px\nassert np.isclose(depth_m, 3)\nprint(depth_m)",
        internals="The lab generates a known depth surface, converts it to disparity, adds measured pixel noise and recovers depth with invalid-value masking. It also visualizes first-order uncertainty.",
        experiment="Add the same disparity noise at 2 m and 6 m. Compare depth MAE and explain the nonlinear difference.",
        pitfall="A visually smooth depth map can be consistently wrong in scale. Depth Z and Euclidean range are different away from the optical axis.",
        challenge="Build a depth report that includes valid fraction, MAE by distance range and an uncertainty overlay.",
        reference="https://docs.opencv.org/4.x/dd/d53/tutorial_py_depthmap.html",
        scratch="geometry.disparity_to_depth",
    ),
    46: dict(
        overview="Stereo vision searches for corresponding image points between cameras. Rectification makes ideal matches lie on the same row, reducing a two-dimensional search to a horizontal disparity search. Matching still struggles with occlusion, textureless areas and repeated patterns.",
        titles=[
            "Rectification and disparity hypotheses",
            "Block matching from scratch",
            "SGBM and consistency checks",
        ],
        lessons=[
            "Rectification remaps calibrated views so epipolar lines align horizontally. The lab starts with already rectified synthetic images to isolate matching. A disparity hypothesis shifts one image relative to the other; only overlapping valid pixels should contribute to its comparison cost.",
            "Block matching aggregates a photometric difference over a neighborhood for each candidate disparity and selects the minimum. Larger windows stabilize noisy texture but blur depth boundaries. Costs may use absolute difference, squared difference or robust descriptors. The reference uses absolute differences and a box-filter aggregation.",
            "Semi-global matching adds smoothness constraints along multiple directions while permitting discontinuities. OpenCV StereoSGBM returns fixed-point disparities scaled by 16. Check invalid values and left-right consistency before converting to depth. The generated plane is deliberately easier than a real stereo scene.",
        ],
        math=r"d^*(p)=\arg\min_d\sum_{q\in W(p)}|L(q)-R(q-(d,0))|",
        symbols="L and R are rectified images, W(p) a neighborhood around pixel p and d a candidate disparity. The selected disparity minimizes local absolute intensity difference. Candidate costs [9,2,7] select the second candidate.",
        example="candidate_disparities = np.array([0, 1, 2])\ncosts = np.array([9., 2., 7.])\nbest = candidate_disparities[costs.argmin()]\nassert best == 1\nprint(best)",
        internals="The reference constructs a cost volume over integer shifts and chooses its minimum. SGBM provides an optimized comparison; error is evaluated only in an interior region with valid synthetic correspondences.",
        experiment="Replace random texture with a flat patch and inspect ambiguity in the full cost curve. Add an occluder visible to only one camera.",
        pitfall="Using raw SGBM integer output as pixels makes depth wrong by a factor of 16. Rectification does not create missing correspondence in occluded regions.",
        challenge="Build a stereo-depth pipeline with calibration files, invalid masks and a left-right consistency diagnostic.",
        reference="https://docs.opencv.org/4.x/d2/d85/classcv_1_1StereoSGBM.html",
        scratch="geometry.disparity_to_depth",
    ),
    47: dict(
        overview="A point cloud is a set of 3D samples, often with color, normals or confidence. Unlike an image, it has no guaranteed regular grid. Sampling density, outliers and coordinate conventions affect every downstream geometric operation.",
        titles=[
            "Backprojection and point-cloud structure",
            "Voxel sampling and nearest neighbors",
            "Rigid alignment and ICP",
        ],
        lessons=[
            "A depth map can be backprojected through inverse intrinsics to produce camera-frame points. Filter invalid depth before geometric processing. PLY and other point formats may carry color and normals. Units and frame names must accompany files because coordinates alone do not reveal whether values are meters or millimeters.",
            "Voxel downsampling divides space into cells and replaces points within each cell by a representative such as their mean. It reduces density and memory at the cost of small details. A nearest-neighbor tree accelerates geometric queries but does not guarantee that the nearest point is the correct physical correspondence.",
            "With known pairs, Kabsch alignment finds the least-squares rigid rotation and translation through SVD and reflection correction. ICP alternates nearest-neighbor assignment and rigid fitting. It needs a reasonable initialization and can converge to a wrong local alignment on symmetric or partially overlapping shapes.",
        ],
        math=r"\min_{R,t}\sum_i\lVert Rp_i+t-q_i\rVert^2",
        symbols="pi and qi are paired 3D points, R a proper rotation and t translation. If every target equals its source plus [1,0,0], identity rotation and that translation give zero residual.",
        example="source = np.array([[0., 0., 0.], [0., 1., 0.], [0., 0., 1.]])\ntranslation = np.array([1., 0., 0.])\ntarget = source + translation\nresidual = np.linalg.norm(source + translation - target, axis=1)\nassert np.allclose(residual, 0)\nprint(residual)",
        internals="The lab compares exact paired rigid fitting with iterative unpaired ICP and plots voxel-reduced points. The optional Open3D workflow reads and writes real point-cloud files.",
        experiment="Increase initial rotation and partial overlap to find ICP failures. Compare point count and geometric detail at several voxel sizes.",
        pitfall="ICP residual can be small for an incorrect symmetric alignment. Voxel size has physical units and must match the cloud scale.",
        challenge="Build a point-cloud registration tool that reports overlap, residuals and transform conventions and visualizes failed alignments.",
        reference="https://www.open3d.org/docs/release/tutorial/pipelines/icp_registration.html",
        scratch="geometry.icp",
    ),
    48: dict(
        overview="A neural radiance field represents a scene with a function that predicts density and appearance at spatial locations and viewing directions. Rendering integrates samples along camera rays. The representation learns through images, but geometric identifiability depends on the available views.",
        titles=[
            "Rays, density and positional encoding",
            "Volume rendering and transmittance",
            "Fit a tiny radiance field",
        ],
        lessons=[
            "A ray starts at a camera origin and advances along a direction. A network can map sampled positions and view directions to density and color. Positional encoding supplies sinusoidal features to represent spatial variation. The local model uses positions only, so it cannot model full view-dependent appearance.",
            "Density becomes opacity over a finite ray segment. Transmittance describes how much light reaches a sample without previous absorption. Each sample’s contribution is its opacity times prior transmittance, and remaining light reaches the background. Differentiable compositing lets image error update the field.",
            "The tiny lab learns an orthographic view of an analytic synthetic volume and compares rendered colors with known targets. Fitting one view is underconstrained and does not demonstrate novel-view reconstruction. A real NeRF workflow requires multiple calibrated views, ray sampling, scene bounds and held-out camera evaluation.",
        ],
        math=r"C=\sum_i T_i(1-e^{-\sigma_i\Delta_i})c_i",
        symbols="σi is density, Δi sample interval, ci color and Ti transmittance before sample i. One sample with opacity 0.5, black color and white background yields final intensity 0.5 after adding the background term.",
        example="opacity, color, background = .5, 0., 1.\nrendered = opacity * color + (1-opacity) * background\nassert np.isclose(rendered, .5)\nprint(rendered)",
        internals="The field uses sinusoidal position features, an MLP and nonnegative density. The differentiable renderer accumulates opacity and transmittance, then a pixel MSE trains the field.",
        experiment="Hold out a camera view in an extended multiview experiment and compare its error with training-view error. Inspect whether density is plausible or merely explains one view.",
        pitfall="Low training-image loss does not prove correct 3D geometry. Ignoring background transmittance darkens empty rays.",
        challenge="Extend the tiny field to several known cameras and evaluate an unseen view with fixed scene bounds and rendering settings.",
        reference="https://arxiv.org/abs/2003.08934",
        scratch="geometry.volume_render",
    ),
    49: dict(
        overview="Optimization changes runtime, memory or storage while controlling output quality. Faster arithmetic is useful only when it improves the actual bottleneck. Measure a representative workload before choosing quantization, pruning, compilation or a different architecture.",
        titles=[
            "Profiling and reliable benchmarks",
            "Quantization and numerical error",
            "ONNX export and runtime parity",
        ],
        lessons=[
            "Separate preprocessing, transfer, model execution and postprocessing time. Warm up the runtime, repeat measurements and report a distribution rather than one sample. GPU operations may be asynchronous and need synchronization for accurate timing. Batch size affects throughput and individual request latency differently.",
            "Symmetric int8 quantization maps floating weights to signed integers using a scale. Reconstructing them reveals rounding error. Smaller stored weights do not automatically mean faster execution: a runtime needs supported quantized kernels. The lab times floating multiplication before and after dequantization and explicitly avoids calling that an int8 speedup.",
            "ONNX is an interchange graph format; export success alone does not prove numerical equivalence or performance. The export script trains TinyCNN, checks its ONNX graph and compares CPU runtime logits on a held-out batch. TensorRT concepts include graph optimization, precision selection and engine compilation, which require compatible target hardware for validation.",
        ],
        math=r"q=clip(round(w/s),-127,127),\quad\hat w=sq",
        symbols="w is a weight, s a positive scale, q its signed int8 code and ŵ the reconstruction. With w=0.26 and s=0.1, q=3 and ŵ=0.3, giving error 0.04.",
        example="weight, scale = .26, .1\nquantized = np.clip(np.rint(weight / scale), -127, 127).astype(np.int8)\nreconstructed = float(quantized) * scale\nassert np.isclose(reconstructed, .3)\nprint(quantized, reconstructed)",
        internals="The local lab records storage and output error for a quantized weight matrix. scripts/export_model.py adds actual graph validation and ONNX Runtime output agreement.",
        experiment="Quantize a weight distribution with an outlier and compare per-tensor and per-channel error. Measure the target runtime rather than extrapolating from file size.",
        pitfall="Benchmarking a first call includes initialization. Numerically close logits can still cross a decision threshold on borderline examples.",
        challenge="Optimize a trained vision model under a latency and quality budget, including preprocessing and end-to-end timing.",
        reference="https://docs.pytorch.org/docs/stable/onnx.html",
        scratch="engineering.quantize_symmetric",
    ),
    50: dict(
        overview="Deployment wraps model behavior in a stable interface. Input validation, preprocessing, versioned outputs and useful failure responses are part of correctness. A local demo becomes a service only when its state, storage and operating assumptions are explicit.",
        titles=[
            "Inference contracts and FastAPI",
            "Persistence, sessions and request ordering",
            "Containers and deployment boundaries",
        ],
        lessons=[
            "An inference contract specifies image formats, maximum size, color order, output coordinates and label meanings. The FastAPI app validates bounded base64 payloads, checks decoded dimensions and returns structured detections plus an overlay. Invalid input should produce a useful client error rather than crash the worker.",
            "Tracking requires per-stream state, so the app creates anonymous sessions and rejects repeated or out-of-order frame IDs. A session lock serializes updates, and SQLite stores numeric event reports without images. The notebook exercises actual routes through an in-process HTTP client and verifies persistence and duplicate rejection.",
            "A container packages the application but does not automatically supply authentication, TLS, quotas or scalable storage. Run the teaching service on localhost first. FastAPI suits APIs; Streamlit and Gradio can provide quick local model interfaces. A production service needs deployment-specific load tests, monitoring and a migration plan for stateful workers.",
        ],
        math=r"L_{end}=L_{decode}+L_{pre}+L_{model}+L_{post}+L_{transport}",
        symbols="Lend is end-to-end latency and the remaining terms are decode, preprocessing, inference, postprocessing and transport times. Components 2,3,10,2,5 milliseconds sum to 22 ms. Server model time alone is only one component.",
        example="components_ms = np.array([2., 3., 10., 2., 5.])\nend_to_end_ms = components_ms.sum()\nassert end_to_end_ms == 22\nprint(end_to_end_ms)",
        internals="The capstone factory constructs an API, per-session engine and SQLite event store. Tests send real request payloads without opening a public network listener.",
        experiment="Send invalid images, duplicate IDs and oversized dimensions. Verify status codes and that failed requests do not create stored events.",
        pitfall="In-memory session state is not shared across server processes. Multiple workers need a deliberate state partitioning or external-state design.",
        challenge="Deploy the local service in a container, add a versioned model artifact and document authentication, scaling and rollback requirements before public exposure.",
        reference="https://fastapi.tiangolo.com/tutorial/",
        scratch="engineering.queue_simulation",
    ),
    51: dict(
        overview="Edge AI runs perception near the sensor on constrained hardware. Memory, power, thermal behavior and supported operators can matter as much as model size. Target-device measurements are necessary because desktop CPU results do not predict every edge accelerator.",
        titles=[
            "Compute, memory and resolution budgets",
            "Model and runtime choices",
            "Target-device evaluation",
        ],
        lessons=[
            "An RGB uint8 frame uses height×width×3 bytes before additional buffers. Intermediate feature maps can use much more memory than the input. Lowering resolution reduces compute but may remove small defects or distant objects. The lab measures memory and edge fidelity across input sizes.",
            "Mobile architectures use operations designed for limited compute, but the fastest model depends on runtime support and memory access. Quantization, operator fusion and hardware accelerators introduce compatibility constraints. A graph that falls back to CPU for unsupported operations may lose the expected speed advantage.",
            "Measure sustained latency, throughput, peak memory, power and thermal throttling on the target device. Include capture, resize, transfers and postprocessing. The repository reports only local CPU measurements for its default experiment and provides a device benchmark worksheet for learners to fill with actual hardware results.",
        ],
        math=r"M=HWCb",
        symbols="M is buffer size in bytes, H,W spatial dimensions, C channels and b bytes per element. A 640×480 RGB uint8 image uses 921600 bytes, excluding object overhead and copies.",
        example="height, width, channels, bytes_per_element = 480, 640, 3, 1\nsize = height * width * channels * bytes_per_element\nassert size == 921600\nprint(size)",
        internals="The lab resizes one generated image, runs Canny repeatedly, records buffer size and compares resized edge masks to the full-resolution algorithm output.",
        experiment="Choose a small-object size and reduce resolution until it disappears. Compare the memory saving with the task-specific quality loss.",
        pitfall="A smaller model file may still allocate large activations. Cold-start and thermally throttled timings answer different operational questions.",
        challenge="Profile one model on a real edge device and publish a reproducible table including temperature, power mode and image resolution.",
        reference="https://onnxruntime.ai/docs/performance/",
        scratch="engineering.quantize_symmetric",
    ),
    52: dict(
        overview="Real-time vision is about meeting timing needs on current frames. Throughput measures completed work per second; latency measures delay; frame age measures how stale a result is. A fast model can still produce unusable output if queues grow without bounds.",
        titles=[
            "Latency, throughput and frame age",
            "Bounded queues and frame dropping",
            "Async pipelines and profiling",
        ],
        lessons=[
            "A source can produce frames faster than the inference stage consumes them. In a FIFO queue, waiting time then grows even if every frame is eventually processed. Batch processing can increase throughput while increasing latency. Decide which timing metric matches the application before optimizing.",
            "A bounded latest-frame queue discards old waiting frames to keep results fresh. This reduces completeness and changes time gaps between observations. Tracking must use timestamps to account for skipped frames. The discrete-event lab compares an unbounded FIFO with a bounded queue using declared service time.",
            "Threads can overlap I/O and native-library work; Python-heavy CPU loops may need vectorization or processes. Async code helps coordinate waiting but does not make CPU inference free. The dashboard permits one in-flight request to bound browser-side accumulation. Measure each stage before adding concurrency.",
        ],
        math=r"\rho=\lambda s",
        symbols="λ is arrival rate in frames/second, s mean service seconds/frame and ρ utilization. At 30 FPS and 0.045 seconds of service, ρ=1.35, so one worker cannot keep up indefinitely without dropping or reducing input.",
        example="arrival_fps, service_seconds = 30., .045\nutilization = arrival_fps * service_seconds\nassert utilization > 1\nprint(utilization)",
        internals="The scheduling simulator advances event times, completes active work and drops the oldest waiting frame when capacity is exceeded. Its output is a simulated latency distribution, not a hardware FPS claim.",
        experiment="Compare FIFO and bounded queues under a service-time spike. Report dropped frames alongside p50 and p95 frame latency.",
        pitfall="Reporting average FPS hides long stalls. Repeated wait calls and unbounded queues can make live results increasingly stale.",
        challenge="Build a bounded video pipeline with timestamps, backpressure, clean shutdown and a latency dashboard.",
        reference="https://docs.python.org/3/library/queue.html",
        scratch="engineering.queue_simulation",
    ),
    53: dict(
        overview="Production computer vision combines data, models, software and operations. A trained checkpoint is one component of a system that must remain observable and maintainable. Monitoring detects changes, while labeled evaluation determines whether those changes hurt the task.",
        titles=[
            "Versioned inference and operational metrics",
            "Data drift and quality monitoring",
            "Release, rollback and incident response",
        ],
        lessons=[
            "Record model version, preprocessing version, label map and configuration with every deployment. Log bounded metadata and avoid unnecessary image retention. Track errors, request counts and latency distributions. A reproducible artifact allows a previous model to be restored when a release causes a regression.",
            "Data drift means the input distribution changed; concept drift means the relationship to the target changed. Histogram-based measures such as PSI can flag an intensity shift but cannot prove accuracy loss or identify its cause. Periodically label an appropriate sample and evaluate by meaningful slices.",
            "A release process moves through development, tests, held-out evaluation, optimization, deployment and monitoring. Shadow or canary operation can compare behavior before full rollout when the infrastructure supports it. The capstone provides local inference, tracking, analytics, SQLite, an API and dashboard; authentication and distributed operations remain explicit engineering extensions.",
        ],
        math=r"PSI=\sum_b(p_b-q_b)\log(p_b/q_b)",
        symbols="pb and qb are current and reference proportions in fixed bins. Small smoothing avoids division by zero. PSI is zero for identical distributions; its thresholds are context-dependent and do not measure model accuracy.",
        example="reference = np.array([.5, .5])\ncurrent = np.array([.5, .5])\npsi = np.sum((current-reference) * np.log(current/reference))\nassert np.isclose(psi, 0)\nprint(psi)",
        internals="The lab processes a generated video through the engine, persists real numeric events and measures an injected intensity distribution shift. The capstone links these stages to API and dashboard behavior.",
        experiment="Introduce a brightness shift without changing object labels, then a label change without a large brightness shift. Explain which monitoring signal detects each.",
        pitfall="No drift alert does not imply no accuracy degradation. A dashboard full of metrics is unhelpful without thresholds, ownership and response actions.",
        challenge="Run a controlled model-release exercise with a baseline, acceptance criteria, a simulated regression and a verified rollback procedure.",
        reference="https://docs.python.org/3/library/logging.html",
        scratch="engineering.population_stability",
    ),
}
