"""Authored notes for detection, recognition, learning and temporal vision."""

CONTENT = {
    19: dict(
        overview="Face detection locates face-like regions. It does not identify a person, estimate trustworthiness or infer sensitive traits. Classical and learned detectors use different representations, but all require careful evaluation across pose, lighting, scale and the intended population.",
        titles=[
            "Integral images and Haar features",
            "HOG and sliding-window detectors",
            "Modern detectors and evaluation",
        ],
        lessons=[
            "An integral image stores the cumulative sum above and to the left of each position. Rectangle sums then require four array accesses, which makes Haar rectangle features inexpensive. A cascade rejects easy negative windows early and spends more computation on promising regions. Its learned thresholds come from training examples, not the integral-image formula itself.",
            "HOG divides a neighborhood into cells and summarizes gradient orientations. The full descriptor also uses overlapping block normalization to reduce contrast sensitivity. A linear classifier can score windows at multiple scales. The included NumPy HOG is a simplified cell-normalized teaching version; it is not a reproduction of a trained face detector.",
            "Modern convolutional face detectors jointly predict boxes, scores and sometimes landmarks. The lab loads OpenCV’s bundled Haar cascade and runs it on a cartoon solely to exercise the API. No human-face recall is claimed. Real evaluation requires consented, documented imagery and separate analysis of missed and false detections.",
        ],
        math=r"S(x,y)=\sum_{u\le x,v\le y}I(u,v)",
        symbols="S is an integral image and I the original intensity. A padded integral image makes rectangle sums uniform. For the 2×2 values [[1,2],[3,4]], the full rectangle sum is 10.",
        example="image = np.array([[1, 2], [3, 4]])\nintegral = np.pad(image.cumsum(0).cumsum(1), ((1, 0), (1, 0)))\ntotal = integral[2, 2] - integral[0, 2] - integral[2, 0] + integral[0, 0]\nassert total == 10\nprint(total)",
        internals="The lab visualizes an integral image, orientation histograms and actual cascade boxes. Empty detections are a valid outcome on the synthetic cartoon.",
        experiment="Test how resizing and contrast affect a detector on a small consented evaluation set; include empty scenes and partial occlusions.",
        pitfall="A detected box is not proof that a person is present. Cascade scores should not be treated as calibrated probabilities.",
        challenge="Build a local face-detection viewer with no image retention, annotated false positives and a documented consented evaluation protocol.",
        reference="https://docs.opencv.org/4.x/db/d28/tutorial_cascade_classifier.html",
        scratch="numerics.hog",
    ),
    20: dict(
        overview="Recognition compares representations to decide whether two observations may share an identity. Verification is a one-to-one comparison; identification searches a gallery. The educational lab uses synthetic vectors and anonymous labels so the decision mechanics can be learned without collecting biometric data.",
        titles=[
            "Embeddings, PCA and distance",
            "Verification thresholds and open sets",
            "Evaluation, consent and failure cases",
        ],
        lessons=[
            "An embedding is a vector intended to preserve useful similarity. PCA projects data onto directions of high variance; it does not automatically learn identity. Face-recognition systems usually train a representation with identity-related supervision and carefully align crops. The synthetic lab separates the geometry of embeddings from those data and training requirements.",
            "Verification compares a pair against a threshold; identification selects among gallery candidates and must also support unknown identities. Euclidean distance depends on vector magnitude unless vectors are normalized. Cosine similarity compares direction. Choose a threshold on validation data for a target false-match rate, then freeze it before testing.",
            "Evaluate false matches, false nonmatches and uncertainty across relevant acquisition conditions. A gallery’s size changes the chance of accidental nearest neighbors. Use informed consent, access control and retention limits for any real biometric extension. Do not infer protected attributes or suitability from an embedding.",
        ],
        math=r"s(a,b)=\frac{a^Tb}{\lVert a\rVert\lVert b\rVert}",
        symbols="a and b are nonzero embedding vectors and s is cosine similarity. For a=[1,0] and b=[1,1], similarity is 1/√2, about 0.707. A threshold is a deployment choice, not a universal constant.",
        example="a, b = np.array([1., 0.]), np.array([1., 1.])\nscore = a @ b / (np.linalg.norm(a) * np.linalg.norm(b))\nassert np.isclose(score, 1 / np.sqrt(2))\nprint(score)",
        internals="Generated cluster prototypes create anonymous identities. PCA and nearest-prototype comparison demonstrate distance and rejection; they do not constitute a pretrained human-face recognition system.",
        experiment="Add unknown synthetic identities and sweep the threshold. Plot false acceptance and false rejection rather than only closed-set accuracy.",
        pitfall="Selecting the threshold on the test set leaks evaluation information. Good synthetic cluster separation is not evidence of biometric performance.",
        challenge="Build an anonymous embedding verifier with an explicit unknown outcome and a validation-only threshold selection report.",
        reference="https://scikit-learn.org/stable/modules/generated/sklearn.decomposition.PCA.html",
        scratch="numerics.softmax",
    ),
    21: dict(
        overview="Optical character recognition converts an image of text into symbols. A useful pipeline distinguishes text detection, geometric cleanup, recognition and layout reconstruction. Blurring, skew, language and font choices can each break a different stage.",
        titles=[
            "Thresholding, deskewing and text regions",
            "Template recognition and sequence errors",
            "Tesseract and learned OCR pipelines",
        ],
        lessons=[
            "Preprocessing should improve separation of strokes from background without deleting punctuation or joining letters. Estimate skew from text-line orientation or reliable foreground geometry, rotate with controlled interpolation and preserve a copy of the original. Thresholding is appropriate for some documents but can harm colored or textured text.",
            "Template matching compares a crop against stored glyph images. It illustrates recognition directly, but needs aligned characters and limited fonts. The lab renders digits, compares normalized templates and reports character errors. Real words require segmentation or sequence models that can handle variable-width characters and context.",
            "Tesseract provides a complete OCR engine with page-segmentation and language options. Modern learned systems often separate text detection from line recognition, sometimes using CTC to align variable-length outputs. scripts/external_models.py includes an opt-in Tesseract workflow. Layout, tables and reading order remain separate engineering tasks.",
        ],
        math=r"CER=(S+D+I)/N",
        symbols="S is substitutions, D deletions, I insertions and N the number of reference characters. One substitution in a five-character word gives CER=0.2. General CER needs an edit-distance alignment; equal-length position errors are only a restricted case.",
        example="substitutions, deletions, insertions, reference_length = 1, 0, 0, 5\ncer = (substitutions + deletions + insertions) / reference_length\nassert np.isclose(cer, .2)\nprint(cer)",
        internals="The local lab uses known fixed-spaced glyphs to isolate template recognition. Its positional character error is explicitly narrower than unrestricted edit-distance CER.",
        experiment="Change blur, rotation and character spacing independently. Identify whether errors arise before or during recognition.",
        pitfall="A higher-resolution resize cannot restore unreadable strokes. OCR confidence is not a guarantee that a number was read correctly.",
        challenge="Build a document OCR pipeline that retains page coordinates, flags low-confidence fields and evaluates with true edit-distance CER.",
        reference="https://tesseract-ocr.github.io/tessdoc/ImproveQuality.html",
        scratch="numerics.otsu",
    ),
    22: dict(
        overview="Machine learning fits a rule from examples rather than specifying every visual condition manually. Features are measured inputs, labels are targets, and a held-out evaluation estimates behavior on new examples. Dataset design is part of the model, not administrative work after training.",
        titles=[
            "Datasets, splits and leakage",
            "Linear classification and optimization",
            "Metrics, confusion and thresholds",
        ],
        lessons=[
            "Separate training, validation and test data before fitting any preprocessing. Training fits parameters, validation selects settings and the test set estimates final performance. Related images from one person, video or production item should stay in one split. Random image splitting can leak nearly identical observations across splits.",
            "A linear classifier scores a weighted combination of features. Logistic regression maps those scores to probabilities and minimizes cross entropy with regularization. A scikit-learn Pipeline fits scaling on training data and applies that fitted transformation to test data. The lab uses packaged handwritten-digit data without a network download.",
            "A confusion matrix counts predicted versus true classes. Precision asks how many predicted positives were correct; recall asks how many true positives were found. F1 balances the two, while ROC-AUC measures ranking across thresholds and needs both classes. Class imbalance and decision costs determine which metric is useful.",
        ],
        math=r"Precision=TP/(TP+FP),\quad Recall=TP/(TP+FN)",
        symbols="TP, FP and FN count true positives, false positives and missed positives. With TP=8, FP=2 and FN=4, precision=0.8 and recall=2/3. Zero denominators need an explicit reporting policy.",
        example="tp, fp, fn = 8, 2, 4\nprecision = tp / (tp + fp)\nrecall = tp / (tp + fn)\nf1 = 2 * precision * recall / (precision + recall)\nprint(precision, recall, f1)",
        internals="A stratified split preserves approximate class proportions; a training-only scaler and LogisticRegression form the pipeline. The confusion matrix is measured on untouched test examples.",
        experiment="Compare raw-pixel and HOG features while keeping the split fixed. Tune settings on validation data before inspecting final test results.",
        pitfall="Fitting a scaler or PCA before splitting leaks test distribution information. Accuracy can hide poor minority-class recall.",
        challenge="Build a defect classifier with grouped splits, a validation-selected operating threshold and a test error analysis.",
        reference="https://scikit-learn.org/stable/common_pitfalls.html",
        scratch="numerics.softmax",
    ),
    23: dict(
        overview="A neural network composes simple differentiable operations. A CNN shares small learned filters across image locations, exploiting local structure. Begin with an explicit small network and derivatives, then connect those operations to a framework training loop.",
        titles=[
            "Perceptrons, loss and backpropagation",
            "Convolution, padding and receptive fields",
            "A tiny trainable CNN",
        ],
        lessons=[
            "A perceptron forms a weighted sum plus bias; a nonlinear activation lets multiple layers express more than one linear map. Forward propagation produces scores, a loss compares them with labels, and backpropagation applies the chain rule to obtain parameter gradients. The NumPy MLP includes explicit derivatives for tanh and softmax cross entropy.",
            "A CNN filter slides over channels and spatial locations with shared weights. Stride controls movement and padding controls borders. Pooling aggregates neighborhoods and expands the effective receptive field. Mathematical convolution reverses a kernel; framework conv2d uses correlation. Learned kernels are updated by loss gradients, unlike fixed Gaussian or Sobel filters.",
            "The tiny CNN combines convolution, ReLU, pooling and a classifier. A training loop clears gradients, computes loss, calls backward and updates weights. Evaluation disables training-specific behavior and gradient recording. Small synthetic shapes make every step runnable on CPU but do not establish real-world classification quality.",
        ],
        math=r"\frac{\partial L}{\partial z_j}=p_j-y_j",
        symbols="z is a class logit, p=softmax(z), y a one-hot label and L single-example cross entropy. For p=[0.2,0.8] and label class 1, the logit gradient is [0.2,−0.2]. Average this gradient over a mean-reduced batch.",
        example="probabilities = np.array([.2, .8])\ntarget = np.array([0., 1.])\nlogit_gradient = probabilities - target\nassert np.isclose(logit_gradient.sum(), 0)\nprint(logit_gradient)",
        internals="Inspect the NumPy weight and bias gradients, then compare a fixed kernel through NumPy correlation and PyTorch conv2d. The final lesson trains a CNN with independent generated test samples.",
        experiment="Remove the activation from a multilayer network and reason about which functions remain possible. Change stride and compute output size before running.",
        pitfall="Calling backward accumulates gradients unless they are cleared. A decreasing training loss does not prove generalization.",
        challenge="Implement a two-layer NumPy classifier with a finite-difference gradient check, then explain each corresponding PyTorch operation.",
        reference="https://docs.pytorch.org/tutorials/beginner/basics/autogradqs_tutorial.html",
        scratch="numerics.mlp_train",
    ),
    24: dict(
        overview="PyTorch manages tensors, differentiable operations and model parameters. Its convenience does not remove responsibilities for split integrity, device handling, training state and reproducible checkpoints. A clear loop makes these responsibilities visible.",
        titles=[
            "Tensors, Dataset and DataLoader",
            "Training, validation and devices",
            "Checkpoints, AMP and experiment records",
        ],
        lessons=[
            "A tensor has shape, dtype and device. A Dataset exposes examples; a DataLoader forms batches and optionally shuffles them. Transforms must preserve label meaning. Images commonly use NCHW in models. Use training augmentation only on training data, and deterministic preprocessing for validation and inference.",
            "Training and evaluation are different modes. model.train enables training behavior; model.eval changes layers such as dropout and batch normalization. Neither by itself disables autograd. Use inference_mode or no_grad for evaluation. Move model and data to the same available device; CPU is a valid default when CUDA is unavailable.",
            "Save a state_dict and record architecture, preprocessing, labels and hyperparameters. A resumable training checkpoint also needs optimizer, scheduler, epoch and RNG state. Mixed precision can improve GPU throughput, but use the supported torch.amp API and measure numeric behavior. The CPU lab verifies an exact weight-save/load logit round trip.",
        ],
        math=r"\theta_{t+1}=\theta_t-\eta\nabla_\theta L",
        symbols="θ represents all trainable parameters, η the learning rate and ∇θL the gradient. A weight 0.5 with gradient 0.2 and step 0.1 updates to 0.48. Adam changes this basic rule using moving gradient statistics.",
        example="weight, gradient, learning_rate = .5, .2, .1\nupdated = weight - learning_rate * gradient\nassert np.isclose(updated, .48)\nprint(updated)",
        internals="The reusable trainer uses a seeded DataLoader, Adam and explicit train/eval transitions. The notebook reloads weights on CPU and compares logits, catching architecture or state mismatches.",
        experiment="Resume a training run with and without optimizer state and compare the first update after resuming. Explain why identical weights alone may not reproduce training.",
        pitfall="Using a shuffled validation sampler does not inherently bias metrics, but applying random training augmentation can make evaluation unstable.",
        challenge="Create a reusable trainer with validation-based checkpoint selection, explicit CPU fallback and a machine-readable experiment manifest.",
        reference="https://docs.pytorch.org/tutorials/beginner/basics/quickstart_tutorial.html",
        scratch="models.train_supervised",
    ),
    25: dict(
        overview="Classification predicts labels for an entire image. Binary, multiclass and multilabel problems have different target and output meanings. Choosing the loss follows from those meanings, not from whichever model is fashionable.",
        titles=[
            "Multiclass CNN classification",
            "Binary decisions and calibration",
            "Multilabel tasks and model families",
        ],
        lessons=[
            "Multiclass classification chooses one of several mutually exclusive labels. Cross entropy accepts raw logits and integer class indices in the common PyTorch form. The synthetic CNN learns circle, square and triangle classes. A held-out confusion matrix reveals which classes are confused, while training curves reveal optimization behavior.",
            "A binary decision applies a threshold to a score. A threshold of 0.5 is a convention, not a cost-optimal rule for every task. Calibration measures whether predicted confidence agrees with empirical frequency. The lab derives a circle-versus-other score from the multiclass model; a dedicated binary model would use its own objective.",
            "Multilabel data can have several true labels per image, requiring independent output probabilities and a multilabel loss such as BCEWithLogitsLoss. ResNet uses residual connections, EfficientNet balances model dimensions, and MobileNet emphasizes efficient operations. The optional workflow supports these pretrained families; the local lesson isolates target encoding and loss mechanics.",
        ],
        math=r"p_k=e^{z_k}/\sum_j e^{z_j}",
        symbols="zk is the logit for class k and pk its softmax probability. Subtracting the largest logit before exponentiation avoids overflow without changing the result. Two equal logits produce probabilities [0.5,0.5].",
        example="logits = np.array([1000., 1000.])\nshifted = logits - logits.max()\nprobability = np.exp(shifted) / np.exp(shifted).sum()\nassert np.allclose(probability, [.5, .5])\nprint(probability)",
        internals="A tiny convolutional backbone and linear head produce logits; the lab trains on generated shapes, measures held-out predictions and contrasts exclusive and independent target encodings.",
        experiment="Create a background-only class and inspect whether confidence on unknown objects falls. Compare macro and micro metrics under class imbalance.",
        pitfall="Softmax forces scores to sum to one even for an out-of-distribution image. A confident prediction is not proof that the image belongs to a known class.",
        challenge="Build a three-class image classifier with an error gallery, calibrated validation threshold and a documented unknown-image policy.",
        reference="https://docs.pytorch.org/vision/stable/models.html",
        scratch="models.TinyCNN",
    ),
    26: dict(
        overview="Transfer learning starts from useful learned features and adapts them to a new task. This can reduce data and training requirements, but success depends on how source and target data relate. Frozen features and fine-tuning answer different experimental questions.",
        titles=[
            "Source pretraining and feature reuse",
            "Frozen backbones and new heads",
            "Fine-tuning under domain shift",
        ],
        lessons=[
            "Early image features often capture edges and textures, while later features become more task-specific. Pretraining on a source task provides an initialization or fixed representation. The CPU lab trains its own source model on synthetic shapes, so the origin of every weight is visible.",
            "Feature extraction freezes backbone parameters and trains a replacement classifier. Freezing requires controlling requires_grad and sometimes layer mode: batch-normalization running statistics can change even when parameter gradients are disabled. The experiment measures actual backbone parameter changes instead of assuming the freeze succeeded.",
            "Fine-tuning updates some or all pretrained layers, usually with careful learning rates and validation. Large updates can destroy useful features; a very different target domain may require more adaptation. The lab creates a brightness shift and compares frozen versus trainable features on independent target samples.",
        ],
        math=r"h=f_{\theta}(x),\qquad z=W h+b",
        symbols="x is an image, fθ the backbone, h its feature vector and W,b the new head. Frozen transfer changes W and b while holding θ fixed. With h=[2,1], W=[0.5,−1] and b=0.2, the score is 0.2.",
        example="features = np.array([2., 1.])\nweights = np.array([.5, -1.])\nscore = weights @ features + .2\nassert np.isclose(score, .2)\nprint(score)",
        internals="The lab snapshots feature parameters, trains the target head or full network and computes the maximum feature change. The reported source model is locally trained, not ImageNet pretrained.",
        experiment="Vary target brightness and compare frozen features with fine-tuning at two learning rates using an unchanged test set.",
        pitfall="Replacing the head without matching the label map can silently swap class meanings. Pretraining data may overlap an evaluation set.",
        challenge="Adapt a classifier to a small industrial dataset and compare scratch, frozen-backbone and fine-tuned baselines under the same split.",
        reference="https://docs.pytorch.org/tutorials/beginner/transfer_learning_tutorial.html",
        scratch="models.train_supervised",
    ),
    27: dict(
        overview="Object detection predicts both location and class. A detector can produce several overlapping proposals, so evaluation must match predictions to ground-truth objects and count duplicates correctly. Localization and classification errors are different failure modes.",
        titles=[
            "Boxes, coordinate formats and IoU",
            "NMS and duplicate predictions",
            "Precision–recall and detector evolution",
        ],
        lessons=[
            "A box can be expressed by two corners or by center, width and height. This repository uses continuous xyxy coordinates with width=x2−x1. Intersection over Union measures overlap relative to combined area. Empty or non-overlapping boxes need well-defined zero overlap.",
            "Greedy NMS keeps the highest-scoring box and removes lower-scoring boxes with excessive overlap, then repeats. Apply class-aware suppression when overlapping objects of different classes can coexist. NMS can remove a real nearby object; modern set-prediction methods may use different duplicate-control mechanisms.",
            "R-CNN classified region proposals, Fast R-CNN shared feature computation, and Faster R-CNN learned proposals. SSD and YOLO developed single-stage prediction paths. AP integrates a precision–recall curve after one-to-one matching; mAP averages AP under specified classes and IoU thresholds. The lab demonstrates AP with preassigned matches, not a full COCO evaluator.",
        ],
        math=r"IoU(A,B)=|A\cap B|/(|A|+|B|-|A\cap B|)",
        symbols="A and B are regions and vertical bars denote area. Two 2×2 boxes overlapping in a 1×1 region have intersection 1, union 7 and IoU=1/7.",
        example="area_a, area_b, intersection = 4., 4., 1.\niou = intersection / (area_a + area_b - intersection)\nassert np.isclose(iou, 1/7)\nprint(iou)",
        internals="The NumPy implementation computes vectorized intersection/union and greedy suppression. Precision/recall are calculated from sorted scores and explicit true/false match flags.",
        experiment="Raise the NMS IoU threshold and explain the effect on crowded scenes versus duplicate boxes. Keep confidence and IoU thresholds distinct.",
        pitfall="AP50 and COCO-style AP across IoU thresholds are not interchangeable. Coordinate off-by-one conventions matter for small objects.",
        challenge="Write a one-class evaluator that performs one-to-one matching before AP calculation and tests duplicate detections explicitly.",
        reference="https://cocodataset.org/#detection-eval",
        scratch="numerics.nms",
    ),
    28: dict(
        overview="YOLO-family detectors predict objects efficiently from shared image features. The exact head, assignment, loss and suppression behavior varies by version. Learn the box and training mechanics first, then use an explicit model configuration for the full library workflow.",
        titles=[
            "Single-stage localization mechanics",
            "Dataset preparation and annotation checks",
            "Training, evaluation, inference and export",
        ],
        lessons=[
            "A dense detector learns location and category predictions from spatial features at one or more scales. Early YOLO used a grid-based formulation; newer families change important details. The CPU lab trains a single-object box regressor to expose normalized target encoding and localization loss. It is intentionally not a reproduction of a named YOLO architecture.",
            "YOLO-format labels commonly store class index and normalized center x, center y, width and height. Annotation errors directly corrupt training. The dataset script generates independent train/validation/test splits, checks coordinate ranges, verifies matching files and rejects duplicate image bytes across splits. Real data also needs source-level grouping.",
            "The optional Ultralytics workflow trains a user-selected model, evaluates the test split, saves annotated inference and exports ONNX. Choose model files explicitly and record the installed version. Validation guides hyperparameters; the held-out test is used after decisions are frozen. Review dataset and dependency licenses before redistribution or deployment.",
        ],
        math=r"c_x=(x_1+x_2)/(2W),\quad w=(x_2-x_1)/W",
        symbols="x1,x2 are horizontal corners and W image width; cx and w are normalized center and width. For corners 20 and 60 in a 100-pixel image, cx=0.4 and w=0.4.",
        example="x1, x2, width = 20., 60., 100.\ncenter_x = (x1 + x2) / (2 * width)\nbox_width = (x2 - x1) / width\nassert np.allclose([center_x, box_width], [.4, .4])\nprint(center_x, box_width)",
        internals="The local regressor predicts normalized cxcywh with a sigmoid and trains against boxes derived from generated masks. Full detector stages are implemented in the optional external workflow and are not executed by default.",
        experiment="Inspect every generated label as an overlay, then intentionally introduce an invalid width and confirm that validation rejects it.",
        pitfall="Training and test images from adjacent video frames can leak scene content. A synthetic regressor loss must not be advertised as YOLO mAP.",
        challenge="Train a custom detector on a documented dataset, produce per-class errors and export a model whose outputs match the training runtime.",
        reference="https://docs.ultralytics.com/modes/train/",
        scratch="numerics.iou",
    ),
    29: dict(
        overview="Object segmentation describes which pixels belong to a foreground region. A binary mask gives finer geometry than a box, enabling measurements of coverage and shape. Before separating categories or individual instances, learn mask representation and overlap metrics.",
        titles=[
            "Binary masks and overlap metrics",
            "Encoder–decoder segmentation",
            "Thresholds and boundary errors",
        ],
        lessons=[
            "A binary target assigns each pixel foreground or background. IoU measures intersection divided by union; Dice doubles the intersection and divides by the sum of mask sizes. Empty masks require a stated convention. Pixel accuracy can be misleading when nearly every pixel is background.",
            "An encoder reduces spatial resolution while learning features; a decoder restores a dense prediction. Skip connections preserve fine spatial information. The tiny U-Net uses a shallow encoder, interpolation and a skip concatenation, then produces one foreground logit per pixel. BCEWithLogitsLoss combines a stable sigmoid with binary cross entropy.",
            "A probability threshold converts logits into a mask. Select it on validation data, since changing it on test images biases evaluation. Boundary errors may be costly even when overall IoU is high. Small defects, thin structures and annotation ambiguity need separate analysis.",
        ],
        math=r"Dice=2|P\cap G|/(|P|+|G|)",
        symbols="P is the predicted foreground and G ground truth. If each contains 10 pixels and 8 overlap, Dice=0.8. The associated IoU is 8/12, not 0.8.",
        example="predicted, truth, intersection = 10., 10., 8.\ndice = 2 * intersection / (predicted + truth)\nassert np.isclose(dice, .8)\nprint(dice)",
        internals="The lab trains on generated images and exact synthetic masks, then measures held-out IoU and Dice. These numbers describe only the stated generated distribution.",
        experiment="Change the foreground threshold and plot precision/recall for foreground pixels. Inspect small objects separately.",
        pitfall="Resize categorical masks with nearest-neighbor interpolation. Bilinear interpolation creates invalid intermediate class IDs.",
        challenge="Build an industrial binary segmentation pipeline with paired-file validation, overlay review and per-object error analysis.",
        reference="https://arxiv.org/abs/1505.04597",
        scratch="models.TinyUNet",
    ),
    30: dict(
        overview="Instance segmentation gives each object its own mask, even when objects share a class. Semantic segmentation alone labels all same-class pixels alike. Separating touching objects therefore requires additional structure, such as markers, proposals or object queries.",
        titles=[
            "Instance IDs versus class labels",
            "Distance transforms and watershed",
            "Mask R-CNN and learned instance masks",
        ],
        lessons=[
            "An instance map stores a distinct ID for every object and usually reserves zero for background. IDs are local identifiers, not semantic categories. Two touching circles should have two instances even though both are foreground. Evaluation must match predicted and true instances before scoring overlap.",
            "A distance transform measures distance from foreground pixels to the nearest background. Local peaks can seed individual objects. Watershed grows labeled regions along a topographic surface and places boundaries where regions meet. Poor markers lead to over-segmentation or merged objects, which makes marker design central to this classical method.",
            "Mask R-CNN adds an instance-mask branch to a two-stage detector and uses RoIAlign to reduce quantization misalignment. The default CPU lesson uses watershed on generated touching shapes; the optional torchvision workflow runs a pretrained Mask R-CNN. Dense crowds and occlusion remain hard because visible boundaries may be incomplete.",
        ],
        math=r"D(p)=\min_{q\in background}\lVert p-q\rVert_2",
        symbols="D(p) is a foreground pixel’s distance to background. For point p=[2,2] and background point q=[2,0], the distance is 2 pixels. Large local distances often occur near object interiors.",
        example="p = np.array([2., 2.])\nq = np.array([2., 0.])\ndistance = np.linalg.norm(p - q)\nassert distance == 2\nprint(distance)",
        internals="The lab computes a foreground mask, distance map, marker labels and watershed boundaries. Counted instances are measured from the resulting IDs, not assumed from the input design.",
        experiment="Move the two circles closer and vary the marker threshold. Identify the point at which seeds merge.",
        pitfall="A separate ID for every connected component fails when objects touch. Instance IDs are not stable track IDs across frames.",
        challenge="Create a touching-parts counter with automatic marker selection and an instance-matching evaluation.",
        reference="https://arxiv.org/abs/1703.06870",
        scratch="numerics.components",
    ),
    31: dict(
        overview="Semantic segmentation assigns a category to every pixel. All pixels of the same category share a label even when they belong to separate objects. Dense prediction requires spatially aligned targets, careful loss design and evaluation across classes.",
        titles=[
            "Dense class targets and FCN",
            "U-Net, DeepLab and context",
            "IoU, imbalance and deployment masks",
        ],
        lessons=[
            "A fully convolutional network replaces image-level classification with spatial logits. For C mutually exclusive classes, logits have shape N×C×H×W and targets typically have integer IDs N×H×W. Binary one-channel segmentation is a special case and uses a different target contract.",
            "U-Net uses skip connections to combine localization and deeper context. DeepLab uses dilated convolutions and multiscale context mechanisms in common variants. Dilation increases receptive field without necessarily reducing output resolution, but can introduce sampling artifacts. The local lab trains a small foreground/background U-Net; optional workflows expose pretrained DeepLab.",
            "Compute a confusion matrix across pixels, derive each class IoU and state how absent classes are handled when averaging. Rare classes and uncertain boundaries require care in loss weighting and metrics. Medical datasets require appropriate permissions and expert validation; educational segmentation outputs are not diagnostic tools.",
        ],
        math=r"IoU_c=TP_c/(TP_c+FP_c+FN_c)",
        symbols="TPc counts pixels correctly assigned class c, FPc pixels incorrectly assigned c and FNc missed class-c pixels. Counts 8,2,4 give IoU=8/14. Mean IoU averages class scores under a declared absent-class policy.",
        example="tp, fp, fn = 8., 2., 4.\nclass_iou = tp / (tp + fp + fn)\nassert np.isclose(class_iou, 8/14)\nprint(class_iou)",
        internals="The baseline is binary semantic segmentation with a shallow U-Net. The same dense-prediction principles extend to C classes by changing head channels, targets and loss together.",
        experiment="Create a rare foreground class and compare unweighted loss with a documented weighting scheme. Report per-class IoU rather than only the mean.",
        pitfall="Colorful mask visualizations are not training targets unless colors are mapped consistently to integer class IDs.",
        challenge="Build a semantic segmentation experiment with class-map validation, ignored-pixel handling and a per-class test report.",
        reference="https://arxiv.org/abs/1606.00915",
        scratch="models.TinyUNet",
    ),
    32: dict(
        overview="Pose estimation locates keypoints such as joints. A skeleton connects selected keypoints into a geometric structure. The output can support motion visualization or repetition counting, but visibility, projection and landmark uncertainty limit interpretation.",
        titles=[
            "Keypoint heatmaps and coordinates",
            "Joint angles and skeleton geometry",
            "Temporal states and exercise counting",
        ],
        lessons=[
            "A heatmap gives a spatial score for one keypoint. Argmax picks its peak; soft-argmax computes an expected coordinate under normalized scores. Temperature controls concentration. Multiple peaks can make the expectation fall between plausible locations, so confidence and multimodality matter.",
            "A joint angle uses two vectors meeting at the joint and the angle between them. Two-dimensional image angles depend on camera viewpoint and are not always anatomical three-dimensional angles. Normalize coordinates consistently and reject zero-length limbs rather than returning an arbitrary angle.",
            "A repetition counter uses a state machine and separate high/low thresholds to avoid counting noise near one threshold. It also needs rules for missing keypoints and incomplete cycles. The lab uses synthetic angles; the optional MediaPipe workflow obtains body landmarks from a user-provided model and image.",
        ],
        math=r"\theta=\arccos\left(\frac{u\cdot v}{\lVert u\rVert\lVert v\rVert}\right)",
        symbols="u and v are limb vectors from the joint and θ their angle. Perpendicular vectors [1,0] and [0,1] give 90 degrees. Clamp the cosine to [−1,1] to handle floating-point roundoff.",
        example="u, v = np.array([1., 0.]), np.array([0., 1.])\ncosine = u @ v / (np.linalg.norm(u) * np.linalg.norm(v))\nangle = np.degrees(np.arccos(np.clip(cosine, -1, 1)))\nassert np.isclose(angle, 90)\nprint(angle)",
        internals="Heatmap decoding, angle computation and hysteresis are separate functions so each can be inspected and tested independently of a pose detector.",
        experiment="Add angular noise around the thresholds and compare a single threshold with hysteresis. Include an incomplete repetition.",
        pitfall="A keypoint detector does not diagnose posture or health. Occluded joints can be guessed incorrectly.",
        challenge="Build an exercise counter that displays visible landmarks, tracks incomplete cycles and pauses when confidence is insufficient.",
        reference="https://ai.google.dev/edge/mediapipe/solutions/vision/pose_landmarker/python",
        scratch="tracking.joint_angle",
    ),
    33: dict(
        overview="Hand tracking combines landmark detection, temporal consistency and a gesture interpretation layer. Landmarks provide coordinates; a gesture controller still needs normalization, state and debouncing. Image-space motion should not automatically become an operating-system action.",
        titles=[
            "Hand landmarks and normalized geometry",
            "Pinch and finger gesture features",
            "Stable interaction and virtual pointers",
        ],
        lessons=[
            "A common hand model uses 21 landmarks, including wrist and finger joints. Coordinates may be normalized to image dimensions and depth may use a model-specific scale. Finger numbering is an API contract, not something to infer from drawing order. Handedness can be affected by mirrored camera views.",
            "A pinch feature can divide thumb–index tip distance by a reference hand length. This reduces sensitivity to image scale, although perspective and foreshortening remain. A static threshold gives a preliminary gesture classifier; temporal smoothing and hysteresis reduce flicker.",
            "A virtual pointer maps a selected landmark into a bounded interaction region, smooths motion and confirms clicks with a state machine. The lab visualizes pointer coordinates without moving the system mouse. The optional detector adapter returns landmarks; a real controller must add explicit user enable/disable controls and a reliable escape action.",
        ],
        math=r"r=\lVert p_{thumb}-p_{index}\rVert/\lVert p_{wrist}-p_{middle}\rVert",
        symbols="r is a scale-normalized pinch ratio. If fingertip distance is 10 pixels and reference hand length 80 pixels, r=0.125. A zero reference length makes the feature invalid.",
        example="tip_distance, reference_length = 10., 80.\npinch_ratio = tip_distance / reference_length\nassert np.isclose(pinch_ratio, .125)\nprint(pinch_ratio)",
        internals="Synthetic landmarks make indexing, distance normalization and pointer mapping inspectable. No live hand accuracy or OS-control behavior is claimed by the default lab.",
        experiment="Scale all landmark coordinates by two and verify that a normalized pinch ratio stays constant. Add noise and inspect click stability.",
        pitfall="Raw pixel thresholds change with distance from the camera. Mirroring the display without adjusting coordinates reverses interaction.",
        challenge="Build a virtual-pointer demo with calibration, dwell selection, debouncing and a visible pause control.",
        reference="https://ai.google.dev/edge/mediapipe/solutions/vision/hand_landmarker/python",
        scratch="tracking.joint_angle",
    ),
    34: dict(
        overview="Action recognition uses temporal information to classify a sequence. A single frame may show a pose but cannot reliably reveal motion direction or order. The choice of temporal representation determines what evidence a model can use.",
        titles=[
            "Sequences and temporal sampling",
            "CNN–RNN and recurrent state",
            "3D CNNs and temporal transformers",
        ],
        lessons=[
            "A clip samples frames over a time interval. Frame rate, stride and clip length control which motions remain visible. Splits should group related clips by source video or actor to avoid leakage. The synthetic lab uses coordinate trajectories so temporal order is the only useful direction cue.",
            "A CNN–RNN pipeline extracts per-frame features and updates a recurrent state over time. A GRU uses gates to control information retention. The local model trains a small GRU to distinguish leftward and rightward trajectories; this demonstrates sequence learning without claiming general human-action recognition.",
            "A 3D convolution spans time and space, while a temporal transformer compares tokens across frames. Both require choices about temporal resolution and compute. A real-time system must consider how much future context it needs: a model that observes an entire clip is not an instantaneous online recognizer.",
        ],
        math=r"v_t=(x_t-x_{t-1})/\Delta t",
        symbols="xt is position at time t, Δt the time interval and vt the finite-difference velocity. Moving from 4 to 7 pixels in 0.1 seconds gives 30 pixels per second. Frame differences without Δt mix speed with frame rate.",
        example="previous, current, dt = 4., 7., .1\nvelocity = (current - previous) / dt\nassert np.isclose(velocity, 30)\nprint(velocity)",
        internals="Generated trajectories become batches of T×2 features; a GRU summarizes them and a head predicts direction. Held-out sequences use an independent random seed.",
        experiment="Reverse each test sequence and check whether the predicted direction changes. Shuffle frame order and measure the damage.",
        pitfall="A model may recognize the background or actor instead of the action. Random clip splitting can make evaluation misleadingly easy.",
        challenge="Build a short-clip recognizer with source-grouped splits and separate measurements of recognition delay and compute latency.",
        reference="https://docs.pytorch.org/docs/stable/generated/torch.nn.GRU.html",
        scratch="models.TinyCNN",
    ),
    35: dict(
        overview="Optical flow estimates apparent pixel motion between frames. It is a dense or sparse correspondence field, not a semantic object tracker. Brightness constancy and local motion assumptions make the problem tractable but can fail under illumination change, occlusion or large motion.",
        titles=[
            "Brightness constancy and the aperture problem",
            "Lucas–Kanade least squares",
            "Pyramids and dense flow",
        ],
        lessons=[
            "Brightness constancy assumes a moving scene point keeps approximately the same image intensity. Linearizing this assumption gives one equation for two motion components, so a single pixel is underdetermined. Along a straight edge, only motion perpendicular to the edge is locally observable: this is the aperture problem.",
            "Lucas–Kanade assumes nearby pixels share a motion vector and solves an overdetermined least-squares system using their gradients. A well-conditioned structure tensor needs gradient variation in two directions. The NumPy reference estimates one small global translation; OpenCV’s pyramidal implementation tracks selected points.",
            "A pyramid handles larger motion by solving at coarse resolution and refining. Farneback estimates dense flow through local polynomial approximations. The lab compares known synthetic translation with sparse and dense estimates, excluding border regions where the warp changes the observation model.",
        ],
        math=r"I_xu+I_yv+I_t=0",
        symbols="Ix,Iy are spatial intensity derivatives, It the temporal derivative and u,v the small displacement components. If Ix=2, Iy=0 and It=−4, horizontal displacement u=2 satisfies the equation, while v remains unconstrained.",
        example="ix, iy, it = 2., 0., -4.\nu, v = 2., 0.\nresidual = ix*u + iy*v + it\nassert np.isclose(residual, 0)\nprint(residual)",
        internals="The reference builds gradient equations and solves least squares. Library comparisons use pyramidal Lucas–Kanade and Farneback; their assumptions and support differ.",
        experiment="Increase translation until the small-motion estimate fails, then compare with pyramidal tracking. Add a uniform brightness offset as a separate failure test.",
        pitfall="A colorful flow image can look plausible even when magnitudes are wrong. Use endpoint error against known displacement.",
        challenge="Build a flow-based motion visualizer that marks poorly conditioned points and separates camera translation from local residual motion.",
        reference="https://docs.opencv.org/4.x/d4/dee/tutorial_optical_flow.html",
        scratch="numerics.lucas_kanade_global",
    ),
    36: dict(
        overview="Multi-object tracking maintains several identities across detections. It combines prediction, association, creation and deletion policies. Detection quality, occlusion and object similarity all affect identity continuity.",
        titles=[
            "Track state and detection association",
            "Hungarian assignment and gating",
            "SORT, DeepSORT and evaluation",
        ],
        lessons=[
            "Each active object has a predicted state and uncertainty. New detections must be assigned to old tracks, left unmatched or used to start new tracks. Independent nearest-neighbor choices can assign two detections to the same track, so association needs a global one-to-one constraint.",
            "The Hungarian algorithm finds a minimum-cost assignment in a cost matrix. Costs can use center distance, box overlap or appearance distance. Gating excludes implausible pairs before accepting assignments. Unmatched tracks predict through short gaps and expire after a declared lifetime.",
            "SORT couples a Kalman box state with assignment; DeepSORT adds learned appearance information to reduce identity errors. The included tracker teaches center-state Kalman/Hungarian mechanics and is not a full reproduction of either. Evaluate identity switches, IDF1 or HOTA using a suitable benchmark, not only detector mAP.",
        ],
        math=r"\min_A\sum_{ij}A_{ij}C_{ij}",
        symbols="Cij is the cost of assigning track i to detection j, and Aij is 1 when that assignment is selected. Each track and detection may appear at most once. Costs [[1,9],[8,2]] favor the diagonal with total cost 3.",
        example="from scipy.optimize import linear_sum_assignment\ncost = np.array([[1., 9.], [8., 2.]])\nrows, columns = linear_sum_assignment(cost)\ntotal = cost[rows, columns].sum()\nassert total == 3\nprint(rows, columns, total)",
        internals="The shared tracker performs prediction, gated Hungarian association and Joseph-form covariance correction. The synthetic lab introduces missed observations and reports a limited nearest-truth identity diagnostic.",
        experiment="Make two trajectories cross, remove observations briefly and compare the ID sequence before and after occlusion.",
        pitfall="Track IDs are temporary anonymous identifiers, not person identities. A detector score is not a track survival probability.",
        challenge="Build a vehicle tracker with timestamp-aware motion, line-crossing counts and a labeled identity-switch evaluation.",
        reference="https://arxiv.org/abs/1602.00763",
        scratch="tracking.KalmanTracker",
    ),
}
